// x-im-monolithic/src/main/webapp/app/entities/customer-relation/customer-relation.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './customer-relation.reducer';
import { ICustomerRelation } from 'app/shared/model/customer-relation.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ICustomerRelationProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class CustomerRelation extends React.Component<ICustomerRelationProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { customerRelationList, match } = this.props;
    return (
      <div>
        <h2 id="customer-relation-heading">
          <Translate contentKey="imApp.customerRelation.home.title">Customer Relations</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="imApp.customerRelation.home.createLabel">Create new Customer Relation</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.customerRelation.remarkName">Remark Name</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.customerRelation.py">Py</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.customerRelation.pinYin">Pin Yin</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.customerRelation.type">Type</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.customerRelation.createdDate">Created Date</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.customerRelation.customer">Customer</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {customerRelationList.map((customerRelation, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${customerRelation.id}`} color="link" size="sm">
                      {customerRelation.id}
                    </Button>
                  </td>
                  <td>{customerRelation.remarkName}</td>
                  <td>{customerRelation.py}</td>
                  <td>{customerRelation.pinYin}</td>
                  <td>{customerRelation.type}</td>
                  <td>
                    <TextFormat type="date" value={customerRelation.createdDate} format={APP_DATE_FORMAT} />
                  </td>
                  <td>
                    {customerRelation.customer ? (
                      <Link to={`customer/${customerRelation.customer.id}`}>{customerRelation.customer.firstName}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${customerRelation.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${customerRelation.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${customerRelation.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ customerRelation }: IRootState) => ({
  customerRelationList: customerRelation.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CustomerRelation);

// x-demo-hybrid-gateway/src/main/webapp/app/entities/customer-relation/customer-relation.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Subscription } from 'rxjs/Subscription';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { CustomerRelation } from './customer-relation.model';
import { CustomerRelationService } from './customer-relation.service';
import { Principal } from '../../shared';

@Component({
    selector: 'jhi-customer-relation',
    templateUrl: './customer-relation.component.html'
})
export class CustomerRelationComponent implements OnInit, OnDestroy {
customerRelations: CustomerRelation[];
    currentAccount: any;
    eventSubscriber: Subscription;

    constructor(
        private customerRelationService: CustomerRelationService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private principal: Principal
    ) {
    }

    loadAll() {
        this.customerRelationService.query().subscribe(
            (res: HttpResponse<CustomerRelation[]>) => {
                this.customerRelations = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }
    ngOnInit() {
        this.loadAll();
        this.principal.identity().then((account) => {
            this.currentAccount = account;
        });
        this.registerChangeInCustomerRelations();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: CustomerRelation) {
        return item.id;
    }
    registerChangeInCustomerRelations() {
        this.eventSubscriber = this.eventManager.subscribe('customerRelationListModification', (response) => this.loadAll());
    }

    private onError(error) {
        this.jhiAlertService.error(error.message, null, null);
    }
}

<div>
    <h2>
        <span jhiTranslate="demoHybridGatewayApp.customerRelation.home.title">Customer Relations</span>
        <button class="btn btn-primary float-right jh-create-entity create-customer-relation" [routerLink]="['/', { outlets: { popup: ['customer-relation-new'] } }]">
            <span class="fa fa-plus"></span>
            <span  jhiTranslate="demoHybridGatewayApp.customerRelation.home.createLabel">
            Create new Customer Relation
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <div class="row">
    </div>
    <br/>
    <div class="table-responsive" *ngIf="customerRelations">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="demoHybridGatewayApp.customerRelation.remarkName">Remark Name</span></th>
            <th><span jhiTranslate="demoHybridGatewayApp.customerRelation.py">Py</span></th>
            <th><span jhiTranslate="demoHybridGatewayApp.customerRelation.pinYin">Pin Yin</span></th>
            <th><span jhiTranslate="demoHybridGatewayApp.customerRelation.type">Type</span></th>
            <th><span jhiTranslate="demoHybridGatewayApp.customerRelation.createdDate">Created Date</span></th>
            <th><span jhiTranslate="demoHybridGatewayApp.customerRelation.customer">Customer</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let customerRelation of customerRelations ;trackBy: trackId">
                <td><a [routerLink]="['../customer-relation', customerRelation.id ]">{{customerRelation.id}}</a></td>
                <td>{{customerRelation.remarkName}}</td>
                <td>{{customerRelation.py}}</td>
                <td>{{customerRelation.pinYin}}</td>
                <td>{{customerRelation.type}}</td>
                <td>{{customerRelation.createdDate | date:'medium'}}</td>
                <td>
                    <div *ngIf="customerRelation.customerId">
                        <a [routerLink]="['../customer', customerRelation.customerId  ]" >{{customerRelation.customerFirstName}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['../customer-relation', customerRelation.id ]"
                                class="btn btn-info btn-sm">
                            <span class="fa fa-eye"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'customer-relation/'+ customerRelation.id + '/edit'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-primary btn-sm">
                            <span class="fa fa-pencil"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'customer-relation/'+ customerRelation.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <span class="fa fa-remove"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
