// x-im-web-new/src/main/webapp/app/entities/customer-relation/customer-relation.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from 'app/entities/customer-relation/customer-relation.reducer';
import { ICustomerRelation } from 'app/shared/model/customer-relation.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ICustomerRelationProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface ICustomerRelationState {
  search: string;
}

export class CustomerRelation extends React.Component<ICustomerRelationProps, ICustomerRelationState> {
  state: ICustomerRelationState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.props.getEntities();
    this.setState({
      search: ''
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { customerRelationList, match } = this.props;
    return (
      <div>
        <h2 id="customer-relation-heading">
          <Translate contentKey="imWebGatewayApp.customerRelation.home.title">Customer Relations</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="imWebGatewayApp.customerRelation.home.createLabel">Create new Customer Relation</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('imWebGatewayApp.customerRelation.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.customerRelation.remarkName">Remark Name</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.customerRelation.py">Py</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.customerRelation.pinYin">Pin Yin</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.customerRelation.type">Type</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.customerRelation.createdDate">Created Date</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.customerRelation.customer">Customer</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {customerRelationList.map((customerRelation, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${customerRelation.id}`} color="link" size="sm">
                      {customerRelation.id}
                    </Button>
                  </td>
                  <td>{customerRelation.remarkName}</td>
                  <td>{customerRelation.py}</td>
                  <td>{customerRelation.pinYin}</td>
                  <td>{customerRelation.type}</td>
                  <td>
                    <TextFormat type="date" value={customerRelation.createdDate} format={APP_DATE_FORMAT} />
                  </td>
                  <td>
                    {customerRelation.customerFirstName ? (
                      <Link to={`customer/${customerRelation.customerId}`}>{customerRelation.customerFirstName}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${customerRelation.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${customerRelation.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${customerRelation.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ customerRelation }: IRootState) => ({
  customerRelationList: customerRelation.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CustomerRelation);

// x-im-desktop-gateway/src/main/webapp/app/entities/customer-relation/customer-relation.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { ICustomerRelation } from 'app/shared/model/customer-relation.model';
import { Principal } from 'app/core';
import { CustomerRelationService } from './customer-relation.service';

@Component({
    selector: 'jhi-customer-relation',
    templateUrl: './customer-relation.component.html'
})
export class CustomerRelationComponent implements OnInit, OnDestroy {
    customerRelations: ICustomerRelation[];
    currentAccount: any;
    eventSubscriber: Subscription;
    currentSearch: string;

    constructor(
        private customerRelationService: CustomerRelationService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private activatedRoute: ActivatedRoute,
        private principal: Principal
    ) {
        this.currentSearch =
            this.activatedRoute.snapshot && this.activatedRoute.snapshot.params['search']
                ? this.activatedRoute.snapshot.params['search']
                : '';
    }

    loadAll() {
        if (this.currentSearch) {
            this.customerRelationService
                .search({
                    query: this.currentSearch
                })
                .subscribe(
                    (res: HttpResponse<ICustomerRelation[]>) => (this.customerRelations = res.body),
                    (res: HttpErrorResponse) => this.onError(res.message)
                );
            return;
        }
        this.customerRelationService.query().subscribe(
            (res: HttpResponse<ICustomerRelation[]>) => {
                this.customerRelations = res.body;
                this.currentSearch = '';
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    search(query) {
        if (!query) {
            return this.clear();
        }
        this.currentSearch = query;
        this.loadAll();
    }

    clear() {
        this.currentSearch = '';
        this.loadAll();
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInCustomerRelations();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: ICustomerRelation) {
        return item.id;
    }

    registerChangeInCustomerRelations() {
        this.eventSubscriber = this.eventManager.subscribe('customerRelationListModification', response => this.loadAll());
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="imGatewayApp.customerRelation.home.title">Customer Relations</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-customer-relation" [routerLink]="['/customer-relation/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span class="hidden-sm-down"  jhiTranslate="imGatewayApp.customerRelation.home.createLabel">
            Create new Customer Relation
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'imGatewayApp.customerRelation.home.search' | translate }}">
                    <button class="input-group-append btn btn-info" (click)="search(currentSearch)">
                        <fa-icon [icon]="'search'"></fa-icon>
                    </button>
                    <button class="input-group-append btn btn-danger" (click)="clear()" *ngIf="currentSearch">
                        <fa-icon [icon]="'trash-alt'"></fa-icon>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br/>
    <div class="table-responsive" *ngIf="customerRelations">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="imGatewayApp.customerRelation.remarkName">Remark Name</span></th>
            <th><span jhiTranslate="imGatewayApp.customerRelation.py">Py</span></th>
            <th><span jhiTranslate="imGatewayApp.customerRelation.pinYin">Pin Yin</span></th>
            <th><span jhiTranslate="imGatewayApp.customerRelation.type">Type</span></th>
            <th><span jhiTranslate="imGatewayApp.customerRelation.createdDate">Created Date</span></th>
            <th><span jhiTranslate="imGatewayApp.customerRelation.customer">Customer</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let customerRelation of customerRelations ;trackBy: trackId">
                <td><a [routerLink]="['/customer-relation', customerRelation.id, 'view' ]">{{customerRelation.id}}</a></td>
                <td>{{customerRelation.remarkName}}</td>
                <td>{{customerRelation.py}}</td>
                <td>{{customerRelation.pinYin}}</td>
                <td>{{customerRelation.type}}</td>
                <td>{{customerRelation.createdDate | date:'medium'}}</td>
                <td>
                    <div *ngIf="customerRelation.customerId">
                        <a [routerLink]="['../customer', customerRelation.customerId , 'view' ]" >{{customerRelation.customerFirstName}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/customer-relation', customerRelation.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/customer-relation', customerRelation.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'customer-relation/'+ customerRelation.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
