// x-manage-web/src/main/webapp/app/entities/dialogue/dialogue-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label, UncontrolledTooltip } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './dialogue.reducer';
import { IDialogue } from 'app/shared/model/dialogue.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { keysToValues } from 'app/shared/util/entity-utils';

export interface IDialogueUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: number }> {}

export interface IDialogueUpdateState {
  isNew: boolean;
}

export class DialogueUpdate extends React.Component<IDialogueUpdateProps, IDialogueUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }
  }

  saveEntity = (event, errors, values) => {
    values.createdDate = new Date(values.createdDate);

    if (errors.length === 0) {
      const { dialogueEntity } = this.props;
      const entity = {
        ...dialogueEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
      this.handleClose();
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/dialogue');
  };

  render() {
    const { dialogueEntity, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="manageGatewayApp.dialogue.home.createOrEditLabel">
              <Translate contentKey="manageGatewayApp.dialogue.home.createOrEditLabel">Create or edit a Dialogue</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : dialogueEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="dialogue-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="createdDateLabel" for="createdDate">
                    <Translate contentKey="manageGatewayApp.dialogue.createdDate">Created Date</Translate>
                  </Label>
                  <AvInput
                    id="dialogue-createdDate"
                    type="datetime-local"
                    className="form-control"
                    name="createdDate"
                    value={isNew ? null : convertDateTimeFromServer(this.props.dialogueEntity.createdDate)}
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                  <UncontrolledTooltip target="createdDateLabel">
                    <Translate contentKey="manageGatewayApp.dialogue.help.createdDate" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="createdIdLabel" for="createdId">
                    <Translate contentKey="manageGatewayApp.dialogue.createdId">Created Id</Translate>
                  </Label>
                  <AvField
                    id="dialogue-createdId"
                    type="number"
                    className="form-control"
                    name="createdId"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      number: { value: true, errorMessage: translate('entity.validation.number') }
                    }}
                  />
                  <UncontrolledTooltip target="createdIdLabel">
                    <Translate contentKey="manageGatewayApp.dialogue.help.createdId" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="targetIdLabel" for="targetId">
                    <Translate contentKey="manageGatewayApp.dialogue.targetId">Target Id</Translate>
                  </Label>
                  <AvField
                    id="dialogue-targetId"
                    type="number"
                    className="form-control"
                    name="targetId"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      number: { value: true, errorMessage: translate('entity.validation.number') }
                    }}
                  />
                  <UncontrolledTooltip target="targetIdLabel">
                    <Translate contentKey="manageGatewayApp.dialogue.help.targetId" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="targetTypeLabel" for="targetType">
                    <Translate contentKey="manageGatewayApp.dialogue.targetType">Target Type</Translate>
                  </Label>
                  <AvField
                    id="dialogue-targetType"
                    type="text"
                    name="targetType"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 2, errorMessage: translate('entity.validation.maxlength', { max: 2 }) }
                    }}
                  />
                  <UncontrolledTooltip target="targetTypeLabel">
                    <Translate contentKey="manageGatewayApp.dialogue.help.targetType" />
                  </UncontrolledTooltip>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/dialogue" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />&nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />&nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  dialogueEntity: storeState.dialogue.entity,
  loading: storeState.dialogue.loading,
  updating: storeState.dialogue.updating
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(DialogueUpdate);

// x-im-desktop-gateway/src/main/webapp/app/entities/dialogue/dialogue-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import * as moment from 'moment';
import { DATE_TIME_FORMAT } from 'app/shared/constants/input.constants';

import { IDialogue } from 'app/shared/model/dialogue.model';
import { DialogueService } from './dialogue.service';

@Component({
    selector: 'jhi-dialogue-update',
    templateUrl: './dialogue-update.component.html'
})
export class DialogueUpdateComponent implements OnInit {
    private _dialogue: IDialogue;
    isSaving: boolean;
    createdDate: string;

    constructor(private dialogueService: DialogueService, private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ dialogue }) => {
            this.dialogue = dialogue;
        });
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        this.dialogue.createdDate = moment(this.createdDate, DATE_TIME_FORMAT);
        if (this.dialogue.id !== undefined) {
            this.subscribeToSaveResponse(this.dialogueService.update(this.dialogue));
        } else {
            this.subscribeToSaveResponse(this.dialogueService.create(this.dialogue));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<IDialogue>>) {
        result.subscribe((res: HttpResponse<IDialogue>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }
    get dialogue() {
        return this._dialogue;
    }

    set dialogue(dialogue: IDialogue) {
        this._dialogue = dialogue;
        this.createdDate = moment(dialogue.createdDate).format(DATE_TIME_FORMAT);
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="jhi-dialogue-heading" jhiTranslate="imGatewayApp.dialogue.home.createOrEditLabel">Create or edit a Dialogue</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!dialogue.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="dialogue.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.dialogue.createdDate" for="field_createdDate" [ngbTooltip]="'imGatewayApp.dialogue.help.createdDate' | translate">Created Date</label>
                    <div class="d-flex">
                        <input id="field_createdDate" type="datetime-local" class="form-control" name="createdDate" [(ngModel)]="createdDate"
                        required/>
                    </div>
                    <div [hidden]="!(editForm.controls.createdDate?.dirty && editForm.controls.createdDate?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.createdDate?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.createdDate?.errors?.ZonedDateTimelocal" jhiTranslate="entity.validation.ZonedDateTimelocal">
                            This field should be a date and time.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.dialogue.createdId" for="field_createdId" [ngbTooltip]="'imGatewayApp.dialogue.help.createdId' | translate">Created Id</label>
                    <input type="number" class="form-control" name="createdId" id="field_createdId"
                        [(ngModel)]="dialogue.createdId" required/>
                    <div [hidden]="!(editForm.controls.createdId?.dirty && editForm.controls.createdId?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.createdId?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.createdId?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.dialogue.targetId" for="field_targetId" [ngbTooltip]="'imGatewayApp.dialogue.help.targetId' | translate">Target Id</label>
                    <input type="number" class="form-control" name="targetId" id="field_targetId"
                        [(ngModel)]="dialogue.targetId" required/>
                    <div [hidden]="!(editForm.controls.targetId?.dirty && editForm.controls.targetId?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.targetId?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.targetId?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.dialogue.targetType" for="field_targetType" [ngbTooltip]="'imGatewayApp.dialogue.help.targetType' | translate">Target Type</label>
                    <input type="text" class="form-control" name="targetType" id="field_targetType"
                        [(ngModel)]="dialogue.targetType" required minlength="1" maxlength="2"/>
                    <div [hidden]="!(editForm.controls.targetType?.dirty && editForm.controls.targetType?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.targetType?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.targetType?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.targetType?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 2 }">
                        This field cannot be longer than 2 characters.
                        </small>
                    </div>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
