// x-im-monolithic/src/main/webapp/app/entities/dialogue/dialogue-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, UncontrolledTooltip, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './dialogue.reducer';
import { IDialogue } from 'app/shared/model/dialogue.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IDialogueDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class DialogueDetail extends React.Component<IDialogueDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { dialogueEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="imApp.dialogue.detail.title">Dialogue</Translate> [<b>{dialogueEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="createdDate">
                <Translate contentKey="imApp.dialogue.createdDate">Created Date</Translate>
              </span>
              <UncontrolledTooltip target="createdDate">
                <Translate contentKey="imApp.dialogue.help.createdDate" />
              </UncontrolledTooltip>
            </dt>
            <dd>
              <TextFormat value={dialogueEntity.createdDate} type="date" format={APP_DATE_FORMAT} />
            </dd>
            <dt>
              <span id="createdId">
                <Translate contentKey="imApp.dialogue.createdId">Created Id</Translate>
              </span>
              <UncontrolledTooltip target="createdId">
                <Translate contentKey="imApp.dialogue.help.createdId" />
              </UncontrolledTooltip>
            </dt>
            <dd>{dialogueEntity.createdId}</dd>
            <dt>
              <span id="targetId">
                <Translate contentKey="imApp.dialogue.targetId">Target Id</Translate>
              </span>
              <UncontrolledTooltip target="targetId">
                <Translate contentKey="imApp.dialogue.help.targetId" />
              </UncontrolledTooltip>
            </dt>
            <dd>{dialogueEntity.targetId}</dd>
            <dt>
              <span id="targetType">
                <Translate contentKey="imApp.dialogue.targetType">Target Type</Translate>
              </span>
              <UncontrolledTooltip target="targetType">
                <Translate contentKey="imApp.dialogue.help.targetType" />
              </UncontrolledTooltip>
            </dt>
            <dd>{dialogueEntity.targetType}</dd>
          </dl>
          <Button tag={Link} to="/entity/dialogue" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/dialogue/${dialogueEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ dialogue }: IRootState) => ({
  dialogueEntity: dialogue.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(DialogueDetail);

// x-im-desktop-gateway/src/main/webapp/app/entities/dialogue/dialogue-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IDialogue } from 'app/shared/model/dialogue.model';

@Component({
    selector: 'jhi-dialogue-detail',
    templateUrl: './dialogue-detail.component.html'
})
export class DialogueDetailComponent implements OnInit {
    dialogue: IDialogue;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ dialogue }) => {
            this.dialogue = dialogue;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="dialogue">
            <h2><span jhiTranslate="imGatewayApp.dialogue.detail.title">Dialogue</span> {{dialogue.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="imGatewayApp.dialogue.createdDate" [ngbTooltip]="'imGatewayApp.dialogue.help.createdDate' | translate">Created Date</span></dt>
                <dd>
                    <span>{{dialogue.createdDate}}</span>
                </dd>
                <dt><span jhiTranslate="imGatewayApp.dialogue.createdId" [ngbTooltip]="'imGatewayApp.dialogue.help.createdId' | translate">Created Id</span></dt>
                <dd>
                    <span>{{dialogue.createdId}}</span>
                </dd>
                <dt><span jhiTranslate="imGatewayApp.dialogue.targetId" [ngbTooltip]="'imGatewayApp.dialogue.help.targetId' | translate">Target Id</span></dt>
                <dd>
                    <span>{{dialogue.targetId}}</span>
                </dd>
                <dt><span jhiTranslate="imGatewayApp.dialogue.targetType" [ngbTooltip]="'imGatewayApp.dialogue.help.targetType' | translate">Target Type</span></dt>
                <dd>
                    <span>{{dialogue.targetType}}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/dialogue', dialogue.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>
