// x-manage-web/src/main/webapp/app/entities/customer/customer-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label, UncontrolledTooltip } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './customer.reducer';
import { ICustomer } from 'app/shared/model/customer.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { keysToValues } from 'app/shared/util/entity-utils';

export interface ICustomerUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: number }> {}

export interface ICustomerUpdateState {
  isNew: boolean;
}

export class CustomerUpdate extends React.Component<ICustomerUpdateProps, ICustomerUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }
  }

  saveEntity = (event, errors, values) => {
    values.resetDate = new Date(values.resetDate);
    values.createdDate = new Date(values.createdDate);

    if (errors.length === 0) {
      const { customerEntity } = this.props;
      const entity = {
        ...customerEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
      this.handleClose();
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/customer');
  };

  render() {
    const { customerEntity, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="manageGatewayApp.customer.home.createOrEditLabel">
              <Translate contentKey="manageGatewayApp.customer.home.createOrEditLabel">Create or edit a Customer</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : customerEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="customer-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="mobileLabel" for="mobile">
                    <Translate contentKey="manageGatewayApp.customer.mobile">Mobile</Translate>
                  </Label>
                  <AvField
                    id="customer-mobile"
                    type="text"
                    name="mobile"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 6, errorMessage: translate('entity.validation.minlength', { min: 6 }) },
                      maxLength: { value: 18, errorMessage: translate('entity.validation.maxlength', { max: 18 }) }
                    }}
                  />
                  <UncontrolledTooltip target="mobileLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.mobile" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="firstNameLabel" for="firstName">
                    <Translate contentKey="manageGatewayApp.customer.firstName">First Name</Translate>
                  </Label>
                  <AvField
                    id="customer-firstName"
                    type="text"
                    name="firstName"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 2, errorMessage: translate('entity.validation.minlength', { min: 2 }) },
                      maxLength: { value: 14, errorMessage: translate('entity.validation.maxlength', { max: 14 }) }
                    }}
                  />
                  <UncontrolledTooltip target="firstNameLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.firstName" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="lastNameLabel" for="lastName">
                    <Translate contentKey="manageGatewayApp.customer.lastName">Last Name</Translate>
                  </Label>
                  <AvField
                    id="customer-lastName"
                    type="text"
                    name="lastName"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 2, errorMessage: translate('entity.validation.minlength', { min: 2 }) },
                      maxLength: { value: 14, errorMessage: translate('entity.validation.maxlength', { max: 14 }) }
                    }}
                  />
                  <UncontrolledTooltip target="lastNameLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.lastName" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="pyLabel" for="py">
                    <Translate contentKey="manageGatewayApp.customer.py">Py</Translate>
                  </Label>
                  <AvField
                    id="customer-py"
                    type="text"
                    name="py"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 255, errorMessage: translate('entity.validation.maxlength', { max: 255 }) }
                    }}
                  />
                  <UncontrolledTooltip target="pyLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.py" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="pinYinLabel" for="pinYin">
                    <Translate contentKey="manageGatewayApp.customer.pinYin">Pin Yin</Translate>
                  </Label>
                  <AvField
                    id="customer-pinYin"
                    type="text"
                    name="pinYin"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 255, errorMessage: translate('entity.validation.maxlength', { max: 255 }) }
                    }}
                  />
                  <UncontrolledTooltip target="pinYinLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.pinYin" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="passwordHashLabel" for="passwordHash">
                    <Translate contentKey="manageGatewayApp.customer.passwordHash">Password Hash</Translate>
                  </Label>
                  <AvField
                    id="customer-passwordHash"
                    type="text"
                    name="passwordHash"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 60, errorMessage: translate('entity.validation.maxlength', { max: 60 }) }
                    }}
                  />
                  <UncontrolledTooltip target="passwordHashLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.passwordHash" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="emailLabel" for="email">
                    <Translate contentKey="manageGatewayApp.customer.email">Email</Translate>
                  </Label>
                  <AvField
                    id="customer-email"
                    type="text"
                    name="email"
                    validate={{
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 100, errorMessage: translate('entity.validation.maxlength', { max: 100 }) }
                    }}
                  />
                  <UncontrolledTooltip target="emailLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.email" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="imageUrlLabel" for="imageUrl">
                    <Translate contentKey="manageGatewayApp.customer.imageUrl">Image Url</Translate>
                  </Label>
                  <AvField
                    id="customer-imageUrl"
                    type="text"
                    name="imageUrl"
                    validate={{
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 100, errorMessage: translate('entity.validation.maxlength', { max: 100 }) }
                    }}
                  />
                  <UncontrolledTooltip target="imageUrlLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.imageUrl" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="activatedLabel" check>
                    <AvInput id="customer-activated" type="checkbox" className="form-control" name="activated" />
                    <Translate contentKey="manageGatewayApp.customer.activated">Activated</Translate>
                  </Label>
                  <UncontrolledTooltip target="activatedLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.activated" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="langKeyLabel" for="langKey">
                    <Translate contentKey="manageGatewayApp.customer.langKey">Lang Key</Translate>
                  </Label>
                  <AvField
                    id="customer-langKey"
                    type="text"
                    name="langKey"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 6, errorMessage: translate('entity.validation.maxlength', { max: 6 }) }
                    }}
                  />
                  <UncontrolledTooltip target="langKeyLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.langKey" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="activationKeyLabel" for="activationKey">
                    <Translate contentKey="manageGatewayApp.customer.activationKey">Activation Key</Translate>
                  </Label>
                  <AvField
                    id="customer-activationKey"
                    type="text"
                    name="activationKey"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 20, errorMessage: translate('entity.validation.maxlength', { max: 20 }) }
                    }}
                  />
                  <UncontrolledTooltip target="activationKeyLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.activationKey" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="resetKeyLabel" for="resetKey">
                    <Translate contentKey="manageGatewayApp.customer.resetKey">Reset Key</Translate>
                  </Label>
                  <AvField
                    id="customer-resetKey"
                    type="text"
                    name="resetKey"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 20, errorMessage: translate('entity.validation.maxlength', { max: 20 }) }
                    }}
                  />
                  <UncontrolledTooltip target="resetKeyLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.resetKey" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="resetDateLabel" for="resetDate">
                    <Translate contentKey="manageGatewayApp.customer.resetDate">Reset Date</Translate>
                  </Label>
                  <AvInput
                    id="customer-resetDate"
                    type="datetime-local"
                    className="form-control"
                    name="resetDate"
                    value={isNew ? null : convertDateTimeFromServer(this.props.customerEntity.resetDate)}
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                  <UncontrolledTooltip target="resetDateLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.resetDate" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="createdByLabel" for="createdBy">
                    <Translate contentKey="manageGatewayApp.customer.createdBy">Created By</Translate>
                  </Label>
                  <AvField
                    id="customer-createdBy"
                    type="text"
                    name="createdBy"
                    validate={{
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 50, errorMessage: translate('entity.validation.maxlength', { max: 50 }) }
                    }}
                  />
                  <UncontrolledTooltip target="createdByLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.createdBy" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="createdDateLabel" for="createdDate">
                    <Translate contentKey="manageGatewayApp.customer.createdDate">Created Date</Translate>
                  </Label>
                  <AvInput
                    id="customer-createdDate"
                    type="datetime-local"
                    className="form-control"
                    name="createdDate"
                    value={isNew ? null : convertDateTimeFromServer(this.props.customerEntity.createdDate)}
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                  <UncontrolledTooltip target="createdDateLabel">
                    <Translate contentKey="manageGatewayApp.customer.help.createdDate" />
                  </UncontrolledTooltip>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/customer" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />&nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />&nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  customerEntity: storeState.customer.entity,
  loading: storeState.customer.loading,
  updating: storeState.customer.updating
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CustomerUpdate);

// x-im-desktop-gateway/src/main/webapp/app/entities/customer/customer-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import * as moment from 'moment';
import { DATE_TIME_FORMAT } from 'app/shared/constants/input.constants';

import { ICustomer } from 'app/shared/model/customer.model';
import { CustomerService } from './customer.service';

@Component({
    selector: 'jhi-customer-update',
    templateUrl: './customer-update.component.html'
})
export class CustomerUpdateComponent implements OnInit {
    private _customer: ICustomer;
    isSaving: boolean;
    resetDate: string;
    createdDate: string;

    constructor(private customerService: CustomerService, private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ customer }) => {
            this.customer = customer;
        });
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        this.customer.resetDate = moment(this.resetDate, DATE_TIME_FORMAT);
        this.customer.createdDate = moment(this.createdDate, DATE_TIME_FORMAT);
        if (this.customer.id !== undefined) {
            this.subscribeToSaveResponse(this.customerService.update(this.customer));
        } else {
            this.subscribeToSaveResponse(this.customerService.create(this.customer));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<ICustomer>>) {
        result.subscribe((res: HttpResponse<ICustomer>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }
    get customer() {
        return this._customer;
    }

    set customer(customer: ICustomer) {
        this._customer = customer;
        this.resetDate = moment(customer.resetDate).format(DATE_TIME_FORMAT);
        this.createdDate = moment(customer.createdDate).format(DATE_TIME_FORMAT);
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="jhi-customer-heading" jhiTranslate="imGatewayApp.customer.home.createOrEditLabel">Create or edit a Customer</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!customer.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="customer.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.mobile" for="field_mobile" [ngbTooltip]="'imGatewayApp.customer.help.mobile' | translate">Mobile</label>
                    <input type="text" class="form-control" name="mobile" id="field_mobile"
                        [(ngModel)]="customer.mobile" required minlength="6" maxlength="18"/>
                    <div [hidden]="!(editForm.controls.mobile?.dirty && editForm.controls.mobile?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.mobile?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.mobile?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 6 }">
                        This field is required to be at least 6 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.mobile?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 18 }">
                        This field cannot be longer than 18 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.firstName" for="field_firstName" [ngbTooltip]="'imGatewayApp.customer.help.firstName' | translate">First Name</label>
                    <input type="text" class="form-control" name="firstName" id="field_firstName"
                        [(ngModel)]="customer.firstName" required minlength="2" maxlength="14"/>
                    <div [hidden]="!(editForm.controls.firstName?.dirty && editForm.controls.firstName?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.firstName?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.firstName?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 2 }">
                        This field is required to be at least 2 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.firstName?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 14 }">
                        This field cannot be longer than 14 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.lastName" for="field_lastName" [ngbTooltip]="'imGatewayApp.customer.help.lastName' | translate">Last Name</label>
                    <input type="text" class="form-control" name="lastName" id="field_lastName"
                        [(ngModel)]="customer.lastName" required minlength="2" maxlength="14"/>
                    <div [hidden]="!(editForm.controls.lastName?.dirty && editForm.controls.lastName?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.lastName?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.lastName?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 2 }">
                        This field is required to be at least 2 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.lastName?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 14 }">
                        This field cannot be longer than 14 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.py" for="field_py" [ngbTooltip]="'imGatewayApp.customer.help.py' | translate">Py</label>
                    <input type="text" class="form-control" name="py" id="field_py"
                        [(ngModel)]="customer.py" required minlength="1" maxlength="255"/>
                    <div [hidden]="!(editForm.controls.py?.dirty && editForm.controls.py?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.py?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.py?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.py?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 255 }">
                        This field cannot be longer than 255 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.pinYin" for="field_pinYin" [ngbTooltip]="'imGatewayApp.customer.help.pinYin' | translate">Pin Yin</label>
                    <input type="text" class="form-control" name="pinYin" id="field_pinYin"
                        [(ngModel)]="customer.pinYin" required minlength="1" maxlength="255"/>
                    <div [hidden]="!(editForm.controls.pinYin?.dirty && editForm.controls.pinYin?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.pinYin?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.pinYin?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.pinYin?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 255 }">
                        This field cannot be longer than 255 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.passwordHash" for="field_passwordHash" [ngbTooltip]="'imGatewayApp.customer.help.passwordHash' | translate">Password Hash</label>
                    <input type="text" class="form-control" name="passwordHash" id="field_passwordHash"
                        [(ngModel)]="customer.passwordHash" required minlength="1" maxlength="60"/>
                    <div [hidden]="!(editForm.controls.passwordHash?.dirty && editForm.controls.passwordHash?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.passwordHash?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.passwordHash?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.passwordHash?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 60 }">
                        This field cannot be longer than 60 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.email" for="field_email" [ngbTooltip]="'imGatewayApp.customer.help.email' | translate">Email</label>
                    <input type="text" class="form-control" name="email" id="field_email"
                        [(ngModel)]="customer.email" minlength="1" maxlength="100"/>
                    <div [hidden]="!(editForm.controls.email?.dirty && editForm.controls.email?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.email?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.email?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 100 }">
                        This field cannot be longer than 100 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.imageUrl" for="field_imageUrl" [ngbTooltip]="'imGatewayApp.customer.help.imageUrl' | translate">Image Url</label>
                    <input type="text" class="form-control" name="imageUrl" id="field_imageUrl"
                        [(ngModel)]="customer.imageUrl" minlength="1" maxlength="100"/>
                    <div [hidden]="!(editForm.controls.imageUrl?.dirty && editForm.controls.imageUrl?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.imageUrl?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.imageUrl?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 100 }">
                        This field cannot be longer than 100 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.activated" for="field_activated" [ngbTooltip]="'imGatewayApp.customer.help.activated' | translate">Activated</label>
                    <input type="checkbox" class="form-control" name="activated" id="field_activated"
                        [(ngModel)]="customer.activated" />
                    <div [hidden]="!(editForm.controls.activated?.dirty && editForm.controls.activated?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.activated?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.langKey" for="field_langKey" [ngbTooltip]="'imGatewayApp.customer.help.langKey' | translate">Lang Key</label>
                    <input type="text" class="form-control" name="langKey" id="field_langKey"
                        [(ngModel)]="customer.langKey" required minlength="1" maxlength="6"/>
                    <div [hidden]="!(editForm.controls.langKey?.dirty && editForm.controls.langKey?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.langKey?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.langKey?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.langKey?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 6 }">
                        This field cannot be longer than 6 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.activationKey" for="field_activationKey" [ngbTooltip]="'imGatewayApp.customer.help.activationKey' | translate">Activation Key</label>
                    <input type="text" class="form-control" name="activationKey" id="field_activationKey"
                        [(ngModel)]="customer.activationKey" required minlength="1" maxlength="20"/>
                    <div [hidden]="!(editForm.controls.activationKey?.dirty && editForm.controls.activationKey?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.activationKey?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.activationKey?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.activationKey?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 20 }">
                        This field cannot be longer than 20 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.resetKey" for="field_resetKey" [ngbTooltip]="'imGatewayApp.customer.help.resetKey' | translate">Reset Key</label>
                    <input type="text" class="form-control" name="resetKey" id="field_resetKey"
                        [(ngModel)]="customer.resetKey" required minlength="1" maxlength="20"/>
                    <div [hidden]="!(editForm.controls.resetKey?.dirty && editForm.controls.resetKey?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.resetKey?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.resetKey?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.resetKey?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 20 }">
                        This field cannot be longer than 20 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.resetDate" for="field_resetDate" [ngbTooltip]="'imGatewayApp.customer.help.resetDate' | translate">Reset Date</label>
                    <div class="d-flex">
                        <input id="field_resetDate" type="datetime-local" class="form-control" name="resetDate" [(ngModel)]="resetDate"
                        required/>
                    </div>
                    <div [hidden]="!(editForm.controls.resetDate?.dirty && editForm.controls.resetDate?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.resetDate?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.resetDate?.errors?.ZonedDateTimelocal" jhiTranslate="entity.validation.ZonedDateTimelocal">
                            This field should be a date and time.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.createdBy" for="field_createdBy" [ngbTooltip]="'imGatewayApp.customer.help.createdBy' | translate">Created By</label>
                    <input type="text" class="form-control" name="createdBy" id="field_createdBy"
                        [(ngModel)]="customer.createdBy" minlength="1" maxlength="50"/>
                    <div [hidden]="!(editForm.controls.createdBy?.dirty && editForm.controls.createdBy?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.createdBy?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.createdBy?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 50 }">
                        This field cannot be longer than 50 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customer.createdDate" for="field_createdDate" [ngbTooltip]="'imGatewayApp.customer.help.createdDate' | translate">Created Date</label>
                    <div class="d-flex">
                        <input id="field_createdDate" type="datetime-local" class="form-control" name="createdDate" [(ngModel)]="createdDate"
                        required/>
                    </div>
                    <div [hidden]="!(editForm.controls.createdDate?.dirty && editForm.controls.createdDate?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.createdDate?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.createdDate?.errors?.ZonedDateTimelocal" jhiTranslate="entity.validation.ZonedDateTimelocal">
                            This field should be a date and time.
                        </small>
                    </div>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
