// x-demo-hybrid-gateway/src/main/webapp/app/entities/flock-relation/flock-relation.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Subscription } from 'rxjs/Subscription';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { FlockRelation } from './flock-relation.model';
import { FlockRelationService } from './flock-relation.service';
import { Principal } from '../../shared';

@Component({
    selector: 'jhi-flock-relation',
    templateUrl: './flock-relation.component.html'
})
export class FlockRelationComponent implements OnInit, OnDestroy {
flockRelations: FlockRelation[];
    currentAccount: any;
    eventSubscriber: Subscription;

    constructor(
        private flockRelationService: FlockRelationService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private principal: Principal
    ) {
    }

    loadAll() {
        this.flockRelationService.query().subscribe(
            (res: HttpResponse<FlockRelation[]>) => {
                this.flockRelations = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }
    ngOnInit() {
        this.loadAll();
        this.principal.identity().then((account) => {
            this.currentAccount = account;
        });
        this.registerChangeInFlockRelations();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: FlockRelation) {
        return item.id;
    }
    registerChangeInFlockRelations() {
        this.eventSubscriber = this.eventManager.subscribe('flockRelationListModification', (response) => this.loadAll());
    }

    private onError(error) {
        this.jhiAlertService.error(error.message, null, null);
    }
}

<div>
    <h2>
        <span jhiTranslate="demoHybridGatewayApp.flockRelation.home.title">Flock Relations</span>
        <button class="btn btn-primary float-right jh-create-entity create-flock-relation" [routerLink]="['/', { outlets: { popup: ['flock-relation-new'] } }]">
            <span class="fa fa-plus"></span>
            <span  jhiTranslate="demoHybridGatewayApp.flockRelation.home.createLabel">
            Create new Flock Relation
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <div class="row">
    </div>
    <br/>
    <div class="table-responsive" *ngIf="flockRelations">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="demoHybridGatewayApp.flockRelation.remarkName">Remark Name</span></th>
            <th><span jhiTranslate="demoHybridGatewayApp.flockRelation.py">Py</span></th>
            <th><span jhiTranslate="demoHybridGatewayApp.flockRelation.pinYin">Pin Yin</span></th>
            <th><span jhiTranslate="demoHybridGatewayApp.flockRelation.type">Type</span></th>
            <th><span jhiTranslate="demoHybridGatewayApp.flockRelation.createdDate">Created Date</span></th>
            <th><span jhiTranslate="demoHybridGatewayApp.flockRelation.customer">Customer</span></th>
            <th><span jhiTranslate="demoHybridGatewayApp.flockRelation.customerFlock">Customer Flock</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let flockRelation of flockRelations ;trackBy: trackId">
                <td><a [routerLink]="['../flock-relation', flockRelation.id ]">{{flockRelation.id}}</a></td>
                <td>{{flockRelation.remarkName}}</td>
                <td>{{flockRelation.py}}</td>
                <td>{{flockRelation.pinYin}}</td>
                <td>{{flockRelation.type}}</td>
                <td>{{flockRelation.createdDate | date:'medium'}}</td>
                <td>
                    <div *ngIf="flockRelation.customerId">
                        <a [routerLink]="['../customer', flockRelation.customerId  ]" >{{flockRelation.customerFirstName}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="flockRelation.customerFlockId">
                        <a [routerLink]="['../customer-flock', flockRelation.customerFlockId  ]" >{{flockRelation.customerFlockName}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['../flock-relation', flockRelation.id ]"
                                class="btn btn-info btn-sm">
                            <span class="fa fa-eye"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'flock-relation/'+ flockRelation.id + '/edit'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-primary btn-sm">
                            <span class="fa fa-pencil"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'flock-relation/'+ flockRelation.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <span class="fa fa-remove"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// x-im-monolithic/src/main/webapp/app/entities/flock-relation/flock-relation.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './flock-relation.reducer';
import { IFlockRelation } from 'app/shared/model/flock-relation.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IFlockRelationProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class FlockRelation extends React.Component<IFlockRelationProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { flockRelationList, match } = this.props;
    return (
      <div>
        <h2 id="flock-relation-heading">
          <Translate contentKey="imApp.flockRelation.home.title">Flock Relations</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="imApp.flockRelation.home.createLabel">Create new Flock Relation</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.remarkName">Remark Name</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.py">Py</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.pinYin">Pin Yin</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.type">Type</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.createdDate">Created Date</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.customer">Customer</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.customerFlock">Customer Flock</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {flockRelationList.map((flockRelation, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${flockRelation.id}`} color="link" size="sm">
                      {flockRelation.id}
                    </Button>
                  </td>
                  <td>{flockRelation.remarkName}</td>
                  <td>{flockRelation.py}</td>
                  <td>{flockRelation.pinYin}</td>
                  <td>{flockRelation.type}</td>
                  <td>
                    <TextFormat type="date" value={flockRelation.createdDate} format={APP_DATE_FORMAT} />
                  </td>
                  <td>
                    {flockRelation.customer ? (
                      <Link to={`customer/${flockRelation.customer.id}`}>{flockRelation.customer.firstName}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td>
                    {flockRelation.customerFlock ? (
                      <Link to={`customer-flock/${flockRelation.customerFlock.id}`}>{flockRelation.customerFlock.name}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${flockRelation.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${flockRelation.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${flockRelation.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ flockRelation }: IRootState) => ({
  flockRelationList: flockRelation.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(FlockRelation);
