// x-im-desktop-gateway/src/main/webapp/app/entities/flock-relation/flock-relation-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IFlockRelation } from 'app/shared/model/flock-relation.model';

@Component({
    selector: 'jhi-flock-relation-detail',
    templateUrl: './flock-relation-detail.component.html'
})
export class FlockRelationDetailComponent implements OnInit {
    flockRelation: IFlockRelation;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ flockRelation }) => {
            this.flockRelation = flockRelation;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="flockRelation">
            <h2><span jhiTranslate="imGatewayApp.flockRelation.detail.title">Flock Relation</span> {{flockRelation.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="imGatewayApp.flockRelation.remarkName" [ngbTooltip]="'imGatewayApp.flockRelation.help.remarkName' | translate">Remark Name</span></dt>
                <dd>
                    <span>{{flockRelation.remarkName}}</span>
                </dd>
                <dt><span jhiTranslate="imGatewayApp.flockRelation.py" [ngbTooltip]="'imGatewayApp.flockRelation.help.py' | translate">Py</span></dt>
                <dd>
                    <span>{{flockRelation.py}}</span>
                </dd>
                <dt><span jhiTranslate="imGatewayApp.flockRelation.pinYin" [ngbTooltip]="'imGatewayApp.flockRelation.help.pinYin' | translate">Pin Yin</span></dt>
                <dd>
                    <span>{{flockRelation.pinYin}}</span>
                </dd>
                <dt><span jhiTranslate="imGatewayApp.flockRelation.type" [ngbTooltip]="'imGatewayApp.flockRelation.help.type' | translate">Type</span></dt>
                <dd>
                    <span>{{flockRelation.type}}</span>
                </dd>
                <dt><span jhiTranslate="imGatewayApp.flockRelation.createdDate" [ngbTooltip]="'imGatewayApp.flockRelation.help.createdDate' | translate">Created Date</span></dt>
                <dd>
                    <span>{{flockRelation.createdDate}}</span>
                </dd>
                <dt><span jhiTranslate="imGatewayApp.flockRelation.customer">Customer</span></dt>
                <dd>
                    <div *ngIf="flockRelation.customerId">
                        <a [routerLink]="['/customer', flockRelation.customerId, 'view']">{{flockRelation.customerFirstName}}</a>
                    </div>
                </dd>
                <dt><span jhiTranslate="imGatewayApp.flockRelation.customerFlock">Customer Flock</span></dt>
                <dd>
                    <div *ngIf="flockRelation.customerFlockId">
                        <a [routerLink]="['/customer-flock', flockRelation.customerFlockId, 'view']">{{flockRelation.customerFlockName}}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/flock-relation', flockRelation.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>

// x-im-monolithic/src/main/webapp/app/entities/flock-relation/flock-relation-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, UncontrolledTooltip, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './flock-relation.reducer';
import { IFlockRelation } from 'app/shared/model/flock-relation.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IFlockRelationDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class FlockRelationDetail extends React.Component<IFlockRelationDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { flockRelationEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="imApp.flockRelation.detail.title">FlockRelation</Translate> [<b>{flockRelationEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="remarkName">
                <Translate contentKey="imApp.flockRelation.remarkName">Remark Name</Translate>
              </span>
              <UncontrolledTooltip target="remarkName">
                <Translate contentKey="imApp.flockRelation.help.remarkName" />
              </UncontrolledTooltip>
            </dt>
            <dd>{flockRelationEntity.remarkName}</dd>
            <dt>
              <span id="py">
                <Translate contentKey="imApp.flockRelation.py">Py</Translate>
              </span>
              <UncontrolledTooltip target="py">
                <Translate contentKey="imApp.flockRelation.help.py" />
              </UncontrolledTooltip>
            </dt>
            <dd>{flockRelationEntity.py}</dd>
            <dt>
              <span id="pinYin">
                <Translate contentKey="imApp.flockRelation.pinYin">Pin Yin</Translate>
              </span>
              <UncontrolledTooltip target="pinYin">
                <Translate contentKey="imApp.flockRelation.help.pinYin" />
              </UncontrolledTooltip>
            </dt>
            <dd>{flockRelationEntity.pinYin}</dd>
            <dt>
              <span id="type">
                <Translate contentKey="imApp.flockRelation.type">Type</Translate>
              </span>
              <UncontrolledTooltip target="type">
                <Translate contentKey="imApp.flockRelation.help.type" />
              </UncontrolledTooltip>
            </dt>
            <dd>{flockRelationEntity.type}</dd>
            <dt>
              <span id="createdDate">
                <Translate contentKey="imApp.flockRelation.createdDate">Created Date</Translate>
              </span>
              <UncontrolledTooltip target="createdDate">
                <Translate contentKey="imApp.flockRelation.help.createdDate" />
              </UncontrolledTooltip>
            </dt>
            <dd>
              <TextFormat value={flockRelationEntity.createdDate} type="date" format={APP_DATE_FORMAT} />
            </dd>
            <dt>
              <Translate contentKey="imApp.flockRelation.customer">Customer</Translate>
            </dt>
            <dd>{flockRelationEntity.customer ? flockRelationEntity.customer.firstName : ''}</dd>
            <dt>
              <Translate contentKey="imApp.flockRelation.customerFlock">Customer Flock</Translate>
            </dt>
            <dd>{flockRelationEntity.customerFlock ? flockRelationEntity.customerFlock.name : ''}</dd>
          </dl>
          <Button tag={Link} to="/entity/flock-relation" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/flock-relation/${flockRelationEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ flockRelation }: IRootState) => ({
  flockRelationEntity: flockRelation.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(FlockRelationDetail);
