// x-demo-gateway/src/main/webapp/app/entities/current-message/current-message-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import * as moment from 'moment';
import { DATE_TIME_FORMAT } from 'app/shared/constants/input.constants';
import { JhiAlertService } from 'ng-jhipster';

import { ICurrentMessage } from 'app/shared/model/current-message.model';
import { CurrentMessageService } from './current-message.service';
import { IDialogue } from 'app/shared/model/dialogue.model';
import { DialogueService } from 'app/entities/dialogue';

@Component({
    selector: 'jhi-current-message-update',
    templateUrl: './current-message-update.component.html'
})
export class CurrentMessageUpdateComponent implements OnInit {
    private _currentMessage: ICurrentMessage;
    isSaving: boolean;

    dialogues: IDialogue[];
    createdDate: string;
    targetDate: string;

    constructor(
        private jhiAlertService: JhiAlertService,
        private currentMessageService: CurrentMessageService,
        private dialogueService: DialogueService,
        private activatedRoute: ActivatedRoute
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ currentMessage }) => {
            this.currentMessage = currentMessage;
        });
        this.dialogueService.query().subscribe(
            (res: HttpResponse<IDialogue[]>) => {
                this.dialogues = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        this.currentMessage.createdDate = moment(this.createdDate, DATE_TIME_FORMAT);
        this.currentMessage.targetDate = moment(this.targetDate, DATE_TIME_FORMAT);
        if (this.currentMessage.id !== undefined) {
            this.subscribeToSaveResponse(this.currentMessageService.update(this.currentMessage));
        } else {
            this.subscribeToSaveResponse(this.currentMessageService.create(this.currentMessage));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<ICurrentMessage>>) {
        result.subscribe((res: HttpResponse<ICurrentMessage>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }

    trackDialogueById(index: number, item: IDialogue) {
        return item.id;
    }
    get currentMessage() {
        return this._currentMessage;
    }

    set currentMessage(currentMessage: ICurrentMessage) {
        this._currentMessage = currentMessage;
        this.createdDate = moment(currentMessage.createdDate).format(DATE_TIME_FORMAT);
        this.targetDate = moment(currentMessage.targetDate).format(DATE_TIME_FORMAT);
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="jhi-current-message-heading" jhiTranslate="demoGatewayApp.currentMessage.home.createOrEditLabel">Create or edit a Current Message</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!currentMessage.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="currentMessage.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="demoGatewayApp.currentMessage.content" for="field_content" [ngbTooltip]="'demoGatewayApp.currentMessage.help.content' | translate">Content</label>
                    <input type="text" class="form-control" name="content" id="field_content"
                        [(ngModel)]="currentMessage.content" minlength="2" maxlength="14"/>
                    <div [hidden]="!(editForm.controls.content?.dirty && editForm.controls.content?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.content?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 2 }">
                        This field is required to be at least 2 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.content?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 14 }">
                        This field cannot be longer than 14 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="demoGatewayApp.currentMessage.status" for="field_status" [ngbTooltip]="'demoGatewayApp.currentMessage.help.status' | translate">Status</label>
                    <input type="text" class="form-control" name="status" id="field_status"
                        [(ngModel)]="currentMessage.status" required minlength="1" maxlength="2"/>
                    <div [hidden]="!(editForm.controls.status?.dirty && editForm.controls.status?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.status?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.status?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.status?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 2 }">
                        This field cannot be longer than 2 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="demoGatewayApp.currentMessage.type" for="field_type" [ngbTooltip]="'demoGatewayApp.currentMessage.help.type' | translate">Type</label>
                    <input type="text" class="form-control" name="type" id="field_type"
                        [(ngModel)]="currentMessage.type" required minlength="1" maxlength="2"/>
                    <div [hidden]="!(editForm.controls.type?.dirty && editForm.controls.type?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.type?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.type?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.type?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 2 }">
                        This field cannot be longer than 2 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="demoGatewayApp.currentMessage.createdDate" for="field_createdDate" [ngbTooltip]="'demoGatewayApp.currentMessage.help.createdDate' | translate">Created Date</label>
                    <div class="d-flex">
                        <input id="field_createdDate" type="datetime-local" class="form-control" name="createdDate" [(ngModel)]="createdDate"
                        required/>
                    </div>
                    <div [hidden]="!(editForm.controls.createdDate?.dirty && editForm.controls.createdDate?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.createdDate?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.createdDate?.errors?.ZonedDateTimelocal" jhiTranslate="entity.validation.ZonedDateTimelocal">
                            This field should be a date and time.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="demoGatewayApp.currentMessage.createdId" for="field_createdId" [ngbTooltip]="'demoGatewayApp.currentMessage.help.createdId' | translate">Created Id</label>
                    <input type="number" class="form-control" name="createdId" id="field_createdId"
                        [(ngModel)]="currentMessage.createdId" required/>
                    <div [hidden]="!(editForm.controls.createdId?.dirty && editForm.controls.createdId?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.createdId?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.createdId?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="demoGatewayApp.currentMessage.targetDate" for="field_targetDate" [ngbTooltip]="'demoGatewayApp.currentMessage.help.targetDate' | translate">Target Date</label>
                    <div class="d-flex">
                        <input id="field_targetDate" type="datetime-local" class="form-control" name="targetDate" [(ngModel)]="targetDate"
                        required/>
                    </div>
                    <div [hidden]="!(editForm.controls.targetDate?.dirty && editForm.controls.targetDate?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.targetDate?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.targetDate?.errors?.ZonedDateTimelocal" jhiTranslate="entity.validation.ZonedDateTimelocal">
                            This field should be a date and time.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="demoGatewayApp.currentMessage.targetId" for="field_targetId" [ngbTooltip]="'demoGatewayApp.currentMessage.help.targetId' | translate">Target Id</label>
                    <input type="number" class="form-control" name="targetId" id="field_targetId"
                        [(ngModel)]="currentMessage.targetId" required/>
                    <div [hidden]="!(editForm.controls.targetId?.dirty && editForm.controls.targetId?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.targetId?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.targetId?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="demoGatewayApp.currentMessage.dialogue" for="field_dialogue">Dialogue</label>
                    <select class="form-control" id="field_dialogue" name="dialogue" [(ngModel)]="currentMessage.dialogueId" >
                        <option [ngValue]="null"></option>
                        <option [ngValue]="dialogueOption.id" *ngFor="let dialogueOption of dialogues; trackBy: trackDialogueById">{{dialogueOption.targetId}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// x-im-web-new/src/main/webapp/app/entities/current-message/current-message-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label, UncontrolledTooltip } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IDialogue } from 'app/shared/model/dialogue.model';
import { getEntities as getDialogues } from 'app/entities/dialogue/dialogue.reducer';
import { getEntity, updateEntity, createEntity, reset } from 'app/entities/current-message/current-message.reducer';
import { ICurrentMessage } from 'app/shared/model/current-message.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { keysToValues } from 'app/shared/util/entity-utils';

export interface ICurrentMessageUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: number }> {}

export interface ICurrentMessageUpdateState {
  isNew: boolean;
  dialogueId: number;
}

export class CurrentMessageUpdate extends React.Component<ICurrentMessageUpdateProps, ICurrentMessageUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      dialogueId: 0,
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getDialogues();
  }

  saveEntity = (event, errors, values) => {
    values.createdDate = new Date(values.createdDate);
    values.targetDate = new Date(values.targetDate);

    if (errors.length === 0) {
      const { currentMessageEntity } = this.props;
      const entity = {
        ...currentMessageEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
      this.handleClose();
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/current-message');
  };

  dialogueUpdate = element => {
    const targetId = element.target.value.toString();
    if (targetId === '') {
      this.setState({
        dialogueId: -1
      });
    } else {
      for (const i in this.props.dialogues) {
        if (targetId === this.props.dialogues[i].targetId.toString()) {
          this.setState({
            dialogueId: this.props.dialogues[i].id
          });
        }
      }
    }
  };

  render() {
    const { currentMessageEntity, dialogues, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="imWebGatewayApp.currentMessage.home.createOrEditLabel">
              <Translate contentKey="imWebGatewayApp.currentMessage.home.createOrEditLabel">Create or edit a CurrentMessage</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : currentMessageEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="current-message-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="contentLabel" for="content">
                    <Translate contentKey="imWebGatewayApp.currentMessage.content">Content</Translate>
                  </Label>
                  <AvField
                    id="current-message-content"
                    type="text"
                    name="content"
                    validate={{
                      minLength: { value: 2, errorMessage: translate('entity.validation.minlength', { min: 2 }) },
                      maxLength: { value: 14, errorMessage: translate('entity.validation.maxlength', { max: 14 }) }
                    }}
                  />
                  <UncontrolledTooltip target="contentLabel">
                    <Translate contentKey="imWebGatewayApp.currentMessage.help.content" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="statusLabel" for="status">
                    <Translate contentKey="imWebGatewayApp.currentMessage.status">Status</Translate>
                  </Label>
                  <AvField
                    id="current-message-status"
                    type="text"
                    name="status"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 2, errorMessage: translate('entity.validation.maxlength', { max: 2 }) }
                    }}
                  />
                  <UncontrolledTooltip target="statusLabel">
                    <Translate contentKey="imWebGatewayApp.currentMessage.help.status" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="typeLabel" for="type">
                    <Translate contentKey="imWebGatewayApp.currentMessage.type">Type</Translate>
                  </Label>
                  <AvField
                    id="current-message-type"
                    type="text"
                    name="type"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 2, errorMessage: translate('entity.validation.maxlength', { max: 2 }) }
                    }}
                  />
                  <UncontrolledTooltip target="typeLabel">
                    <Translate contentKey="imWebGatewayApp.currentMessage.help.type" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="createdDateLabel" for="createdDate">
                    <Translate contentKey="imWebGatewayApp.currentMessage.createdDate">Created Date</Translate>
                  </Label>
                  <AvInput
                    id="current-message-createdDate"
                    type="datetime-local"
                    className="form-control"
                    name="createdDate"
                    value={isNew ? null : convertDateTimeFromServer(this.props.currentMessageEntity.createdDate)}
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                  <UncontrolledTooltip target="createdDateLabel">
                    <Translate contentKey="imWebGatewayApp.currentMessage.help.createdDate" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="createdIdLabel" for="createdId">
                    <Translate contentKey="imWebGatewayApp.currentMessage.createdId">Created Id</Translate>
                  </Label>
                  <AvField
                    id="current-message-createdId"
                    type="number"
                    className="form-control"
                    name="createdId"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      number: { value: true, errorMessage: translate('entity.validation.number') }
                    }}
                  />
                  <UncontrolledTooltip target="createdIdLabel">
                    <Translate contentKey="imWebGatewayApp.currentMessage.help.createdId" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="targetDateLabel" for="targetDate">
                    <Translate contentKey="imWebGatewayApp.currentMessage.targetDate">Target Date</Translate>
                  </Label>
                  <AvInput
                    id="current-message-targetDate"
                    type="datetime-local"
                    className="form-control"
                    name="targetDate"
                    value={isNew ? null : convertDateTimeFromServer(this.props.currentMessageEntity.targetDate)}
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                  <UncontrolledTooltip target="targetDateLabel">
                    <Translate contentKey="imWebGatewayApp.currentMessage.help.targetDate" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="targetIdLabel" for="targetId">
                    <Translate contentKey="imWebGatewayApp.currentMessage.targetId">Target Id</Translate>
                  </Label>
                  <AvField
                    id="current-message-targetId"
                    type="number"
                    className="form-control"
                    name="targetId"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      number: { value: true, errorMessage: translate('entity.validation.number') }
                    }}
                  />
                  <UncontrolledTooltip target="targetIdLabel">
                    <Translate contentKey="imWebGatewayApp.currentMessage.help.targetId" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label for="dialogue.targetId">
                    <Translate contentKey="imWebGatewayApp.currentMessage.dialogue">Dialogue</Translate>
                  </Label>
                  <AvInput
                    id="current-message-dialogue"
                    type="select"
                    className="form-control"
                    name="dialogueId"
                    onChange={this.dialogueUpdate}
                  >
                    <option value="" key="0" />
                    {dialogues
                      ? dialogues.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.targetId}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/current-message" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  dialogues: storeState.dialogue.entities,
  currentMessageEntity: storeState.currentMessage.entity,
  loading: storeState.currentMessage.loading,
  updating: storeState.currentMessage.updating
});

const mapDispatchToProps = {
  getDialogues,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CurrentMessageUpdate);
