// x-demo-gateway/src/main/webapp/app/entities/current-message/current-message.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { ICurrentMessage } from 'app/shared/model/current-message.model';
import { Principal } from 'app/core';
import { CurrentMessageService } from './current-message.service';

@Component({
    selector: 'jhi-current-message',
    templateUrl: './current-message.component.html'
})
export class CurrentMessageComponent implements OnInit, OnDestroy {
    currentMessages: ICurrentMessage[];
    currentAccount: any;
    eventSubscriber: Subscription;
    currentSearch: string;

    constructor(
        private currentMessageService: CurrentMessageService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private activatedRoute: ActivatedRoute,
        private principal: Principal
    ) {
        this.currentSearch =
            this.activatedRoute.snapshot && this.activatedRoute.snapshot.params['search']
                ? this.activatedRoute.snapshot.params['search']
                : '';
    }

    loadAll() {
        if (this.currentSearch) {
            this.currentMessageService
                .search({
                    query: this.currentSearch
                })
                .subscribe(
                    (res: HttpResponse<ICurrentMessage[]>) => (this.currentMessages = res.body),
                    (res: HttpErrorResponse) => this.onError(res.message)
                );
            return;
        }
        this.currentMessageService.query().subscribe(
            (res: HttpResponse<ICurrentMessage[]>) => {
                this.currentMessages = res.body;
                this.currentSearch = '';
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    search(query) {
        if (!query) {
            return this.clear();
        }
        this.currentSearch = query;
        this.loadAll();
    }

    clear() {
        this.currentSearch = '';
        this.loadAll();
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInCurrentMessages();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: ICurrentMessage) {
        return item.id;
    }

    registerChangeInCurrentMessages() {
        this.eventSubscriber = this.eventManager.subscribe('currentMessageListModification', response => this.loadAll());
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="demoGatewayApp.currentMessage.home.title">Current Messages</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-current-message" [routerLink]="['/current-message/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span class="hidden-sm-down"  jhiTranslate="demoGatewayApp.currentMessage.home.createLabel">
            Create new Current Message
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'demoGatewayApp.currentMessage.home.search' | translate }}">
                    <button class="input-group-append btn btn-info" (click)="search(currentSearch)">
                        <fa-icon [icon]="'search'"></fa-icon>
                    </button>
                    <button class="input-group-append btn btn-danger" (click)="clear()" *ngIf="currentSearch">
                        <fa-icon [icon]="'trash-alt'"></fa-icon>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br/>
    <div class="table-responsive" *ngIf="currentMessages">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="demoGatewayApp.currentMessage.content">Content</span></th>
            <th><span jhiTranslate="demoGatewayApp.currentMessage.status">Status</span></th>
            <th><span jhiTranslate="demoGatewayApp.currentMessage.type">Type</span></th>
            <th><span jhiTranslate="demoGatewayApp.currentMessage.createdDate">Created Date</span></th>
            <th><span jhiTranslate="demoGatewayApp.currentMessage.createdId">Created Id</span></th>
            <th><span jhiTranslate="demoGatewayApp.currentMessage.targetDate">Target Date</span></th>
            <th><span jhiTranslate="demoGatewayApp.currentMessage.targetId">Target Id</span></th>
            <th><span jhiTranslate="demoGatewayApp.currentMessage.dialogue">Dialogue</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let currentMessage of currentMessages ;trackBy: trackId">
                <td><a [routerLink]="['/current-message', currentMessage.id, 'view' ]">{{currentMessage.id}}</a></td>
                <td>{{currentMessage.content}}</td>
                <td>{{currentMessage.status}}</td>
                <td>{{currentMessage.type}}</td>
                <td>{{currentMessage.createdDate | date:'medium'}}</td>
                <td>{{currentMessage.createdId}}</td>
                <td>{{currentMessage.targetDate | date:'medium'}}</td>
                <td>{{currentMessage.targetId}}</td>
                <td>
                    <div *ngIf="currentMessage.dialogueId">
                        <a [routerLink]="['../dialogue', currentMessage.dialogueId , 'view' ]" >{{currentMessage.dialogueTargetId}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/current-message', currentMessage.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/current-message', currentMessage.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'current-message/'+ currentMessage.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// x-im-web-new/src/main/webapp/app/entities/current-message/current-message.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from 'app/entities/current-message/current-message.reducer';
import { ICurrentMessage } from 'app/shared/model/current-message.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ICurrentMessageProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface ICurrentMessageState {
  search: string;
}

export class CurrentMessage extends React.Component<ICurrentMessageProps, ICurrentMessageState> {
  state: ICurrentMessageState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.props.getEntities();
    this.setState({
      search: ''
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { currentMessageList, match } = this.props;
    return (
      <div>
        <h2 id="current-message-heading">
          <Translate contentKey="imWebGatewayApp.currentMessage.home.title">Current Messages</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="imWebGatewayApp.currentMessage.home.createLabel">Create new Current Message</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('imWebGatewayApp.currentMessage.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.currentMessage.content">Content</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.currentMessage.status">Status</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.currentMessage.type">Type</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.currentMessage.createdDate">Created Date</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.currentMessage.createdId">Created Id</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.currentMessage.targetDate">Target Date</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.currentMessage.targetId">Target Id</Translate>
                </th>
                <th>
                  <Translate contentKey="imWebGatewayApp.currentMessage.dialogue">Dialogue</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {currentMessageList.map((currentMessage, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${currentMessage.id}`} color="link" size="sm">
                      {currentMessage.id}
                    </Button>
                  </td>
                  <td>{currentMessage.content}</td>
                  <td>{currentMessage.status}</td>
                  <td>{currentMessage.type}</td>
                  <td>
                    <TextFormat type="date" value={currentMessage.createdDate} format={APP_DATE_FORMAT} />
                  </td>
                  <td>{currentMessage.createdId}</td>
                  <td>
                    <TextFormat type="date" value={currentMessage.targetDate} format={APP_DATE_FORMAT} />
                  </td>
                  <td>{currentMessage.targetId}</td>
                  <td>
                    {currentMessage.dialogueTargetId ? (
                      <Link to={`dialogue/${currentMessage.dialogueId}`}>{currentMessage.dialogueTargetId}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${currentMessage.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${currentMessage.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${currentMessage.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ currentMessage }: IRootState) => ({
  currentMessageList: currentMessage.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CurrentMessage);
