// x-im-desktop-gateway/src/main/webapp/app/entities/dialogue/dialogue.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IDialogue } from 'app/shared/model/dialogue.model';
import { Principal } from 'app/core';
import { DialogueService } from './dialogue.service';

@Component({
    selector: 'jhi-dialogue',
    templateUrl: './dialogue.component.html'
})
export class DialogueComponent implements OnInit, OnDestroy {
    dialogues: IDialogue[];
    currentAccount: any;
    eventSubscriber: Subscription;
    currentSearch: string;

    constructor(
        private dialogueService: DialogueService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private activatedRoute: ActivatedRoute,
        private principal: Principal
    ) {
        this.currentSearch =
            this.activatedRoute.snapshot && this.activatedRoute.snapshot.params['search']
                ? this.activatedRoute.snapshot.params['search']
                : '';
    }

    loadAll() {
        if (this.currentSearch) {
            this.dialogueService
                .search({
                    query: this.currentSearch
                })
                .subscribe(
                    (res: HttpResponse<IDialogue[]>) => (this.dialogues = res.body),
                    (res: HttpErrorResponse) => this.onError(res.message)
                );
            return;
        }
        this.dialogueService.query().subscribe(
            (res: HttpResponse<IDialogue[]>) => {
                this.dialogues = res.body;
                this.currentSearch = '';
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    search(query) {
        if (!query) {
            return this.clear();
        }
        this.currentSearch = query;
        this.loadAll();
    }

    clear() {
        this.currentSearch = '';
        this.loadAll();
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInDialogues();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: IDialogue) {
        return item.id;
    }

    registerChangeInDialogues() {
        this.eventSubscriber = this.eventManager.subscribe('dialogueListModification', response => this.loadAll());
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="imGatewayApp.dialogue.home.title">Dialogues</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-dialogue" [routerLink]="['/dialogue/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span class="hidden-sm-down"  jhiTranslate="imGatewayApp.dialogue.home.createLabel">
            Create new Dialogue
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'imGatewayApp.dialogue.home.search' | translate }}">
                    <button class="input-group-append btn btn-info" (click)="search(currentSearch)">
                        <fa-icon [icon]="'search'"></fa-icon>
                    </button>
                    <button class="input-group-append btn btn-danger" (click)="clear()" *ngIf="currentSearch">
                        <fa-icon [icon]="'trash-alt'"></fa-icon>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br/>
    <div class="table-responsive" *ngIf="dialogues">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="imGatewayApp.dialogue.createdDate">Created Date</span></th>
            <th><span jhiTranslate="imGatewayApp.dialogue.createdId">Created Id</span></th>
            <th><span jhiTranslate="imGatewayApp.dialogue.targetId">Target Id</span></th>
            <th><span jhiTranslate="imGatewayApp.dialogue.targetType">Target Type</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let dialogue of dialogues ;trackBy: trackId">
                <td><a [routerLink]="['/dialogue', dialogue.id, 'view' ]">{{dialogue.id}}</a></td>
                <td>{{dialogue.createdDate | date:'medium'}}</td>
                <td>{{dialogue.createdId}}</td>
                <td>{{dialogue.targetId}}</td>
                <td>{{dialogue.targetType}}</td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/dialogue', dialogue.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/dialogue', dialogue.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'dialogue/'+ dialogue.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// x-manage-web/src/main/webapp/app/entities/dialogue/dialogue.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './dialogue.reducer';
import { IDialogue } from 'app/shared/model/dialogue.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IDialogueProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface IDialogueState {
  search: string;
}

export class Dialogue extends React.Component<IDialogueProps, IDialogueState> {
  state: IDialogueState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.props.getEntities();
    this.setState({
      search: ''
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { dialogueList, match } = this.props;
    return (
      <div>
        <h2 id="dialogue-heading">
          <Translate contentKey="manageGatewayApp.dialogue.home.title">Dialogues</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />&nbsp;
            <Translate contentKey="manageGatewayApp.dialogue.home.createLabel">Create new Dialogue</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('manageGatewayApp.dialogue.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="manageGatewayApp.dialogue.createdDate">Created Date</Translate>
                </th>
                <th>
                  <Translate contentKey="manageGatewayApp.dialogue.createdId">Created Id</Translate>
                </th>
                <th>
                  <Translate contentKey="manageGatewayApp.dialogue.targetId">Target Id</Translate>
                </th>
                <th>
                  <Translate contentKey="manageGatewayApp.dialogue.targetType">Target Type</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {dialogueList.map((dialogue, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${dialogue.id}`} color="link" size="sm">
                      {dialogue.id}
                    </Button>
                  </td>
                  <td>
                    <TextFormat type="date" value={dialogue.createdDate} format={APP_DATE_FORMAT} />
                  </td>
                  <td>{dialogue.createdId}</td>
                  <td>{dialogue.targetId}</td>
                  <td>{dialogue.targetType}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${dialogue.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${dialogue.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${dialogue.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ dialogue }: IRootState) => ({
  dialogueList: dialogue.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Dialogue);
