// x-im-monolithic/src/main/webapp/app/entities/flock-relation/flock-relation.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './flock-relation.reducer';
import { IFlockRelation } from 'app/shared/model/flock-relation.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IFlockRelationProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class FlockRelation extends React.Component<IFlockRelationProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { flockRelationList, match } = this.props;
    return (
      <div>
        <h2 id="flock-relation-heading">
          <Translate contentKey="imApp.flockRelation.home.title">Flock Relations</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="imApp.flockRelation.home.createLabel">Create new Flock Relation</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.remarkName">Remark Name</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.py">Py</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.pinYin">Pin Yin</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.type">Type</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.createdDate">Created Date</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.customer">Customer</Translate>
                </th>
                <th>
                  <Translate contentKey="imApp.flockRelation.customerFlock">Customer Flock</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {flockRelationList.map((flockRelation, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${flockRelation.id}`} color="link" size="sm">
                      {flockRelation.id}
                    </Button>
                  </td>
                  <td>{flockRelation.remarkName}</td>
                  <td>{flockRelation.py}</td>
                  <td>{flockRelation.pinYin}</td>
                  <td>{flockRelation.type}</td>
                  <td>
                    <TextFormat type="date" value={flockRelation.createdDate} format={APP_DATE_FORMAT} />
                  </td>
                  <td>
                    {flockRelation.customer ? (
                      <Link to={`customer/${flockRelation.customer.id}`}>{flockRelation.customer.firstName}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td>
                    {flockRelation.customerFlock ? (
                      <Link to={`customer-flock/${flockRelation.customerFlock.id}`}>{flockRelation.customerFlock.name}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${flockRelation.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${flockRelation.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${flockRelation.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ flockRelation }: IRootState) => ({
  flockRelationList: flockRelation.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(FlockRelation);

// x-im-desktop-gateway/src/main/webapp/app/entities/flock-relation/flock-relation.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IFlockRelation } from 'app/shared/model/flock-relation.model';
import { Principal } from 'app/core';
import { FlockRelationService } from './flock-relation.service';

@Component({
    selector: 'jhi-flock-relation',
    templateUrl: './flock-relation.component.html'
})
export class FlockRelationComponent implements OnInit, OnDestroy {
    flockRelations: IFlockRelation[];
    currentAccount: any;
    eventSubscriber: Subscription;
    currentSearch: string;

    constructor(
        private flockRelationService: FlockRelationService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private activatedRoute: ActivatedRoute,
        private principal: Principal
    ) {
        this.currentSearch =
            this.activatedRoute.snapshot && this.activatedRoute.snapshot.params['search']
                ? this.activatedRoute.snapshot.params['search']
                : '';
    }

    loadAll() {
        if (this.currentSearch) {
            this.flockRelationService
                .search({
                    query: this.currentSearch
                })
                .subscribe(
                    (res: HttpResponse<IFlockRelation[]>) => (this.flockRelations = res.body),
                    (res: HttpErrorResponse) => this.onError(res.message)
                );
            return;
        }
        this.flockRelationService.query().subscribe(
            (res: HttpResponse<IFlockRelation[]>) => {
                this.flockRelations = res.body;
                this.currentSearch = '';
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    search(query) {
        if (!query) {
            return this.clear();
        }
        this.currentSearch = query;
        this.loadAll();
    }

    clear() {
        this.currentSearch = '';
        this.loadAll();
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInFlockRelations();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: IFlockRelation) {
        return item.id;
    }

    registerChangeInFlockRelations() {
        this.eventSubscriber = this.eventManager.subscribe('flockRelationListModification', response => this.loadAll());
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="imGatewayApp.flockRelation.home.title">Flock Relations</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-flock-relation" [routerLink]="['/flock-relation/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span class="hidden-sm-down"  jhiTranslate="imGatewayApp.flockRelation.home.createLabel">
            Create new Flock Relation
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'imGatewayApp.flockRelation.home.search' | translate }}">
                    <button class="input-group-append btn btn-info" (click)="search(currentSearch)">
                        <fa-icon [icon]="'search'"></fa-icon>
                    </button>
                    <button class="input-group-append btn btn-danger" (click)="clear()" *ngIf="currentSearch">
                        <fa-icon [icon]="'trash-alt'"></fa-icon>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br/>
    <div class="table-responsive" *ngIf="flockRelations">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="imGatewayApp.flockRelation.remarkName">Remark Name</span></th>
            <th><span jhiTranslate="imGatewayApp.flockRelation.py">Py</span></th>
            <th><span jhiTranslate="imGatewayApp.flockRelation.pinYin">Pin Yin</span></th>
            <th><span jhiTranslate="imGatewayApp.flockRelation.type">Type</span></th>
            <th><span jhiTranslate="imGatewayApp.flockRelation.createdDate">Created Date</span></th>
            <th><span jhiTranslate="imGatewayApp.flockRelation.customer">Customer</span></th>
            <th><span jhiTranslate="imGatewayApp.flockRelation.customerFlock">Customer Flock</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let flockRelation of flockRelations ;trackBy: trackId">
                <td><a [routerLink]="['/flock-relation', flockRelation.id, 'view' ]">{{flockRelation.id}}</a></td>
                <td>{{flockRelation.remarkName}}</td>
                <td>{{flockRelation.py}}</td>
                <td>{{flockRelation.pinYin}}</td>
                <td>{{flockRelation.type}}</td>
                <td>{{flockRelation.createdDate | date:'medium'}}</td>
                <td>
                    <div *ngIf="flockRelation.customerId">
                        <a [routerLink]="['../customer', flockRelation.customerId , 'view' ]" >{{flockRelation.customerFirstName}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="flockRelation.customerFlockId">
                        <a [routerLink]="['../customer-flock', flockRelation.customerFlockId , 'view' ]" >{{flockRelation.customerFlockName}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/flock-relation', flockRelation.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/flock-relation', flockRelation.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'flock-relation/'+ flockRelation.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
