// x-im-desktop-gateway/src/main/webapp/app/entities/flock-relation/flock-relation-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import * as moment from 'moment';
import { DATE_TIME_FORMAT } from 'app/shared/constants/input.constants';
import { JhiAlertService } from 'ng-jhipster';

import { IFlockRelation } from 'app/shared/model/flock-relation.model';
import { FlockRelationService } from './flock-relation.service';
import { ICustomer } from 'app/shared/model/customer.model';
import { CustomerService } from 'app/entities/customer';
import { ICustomerFlock } from 'app/shared/model/customer-flock.model';
import { CustomerFlockService } from 'app/entities/customer-flock';

@Component({
    selector: 'jhi-flock-relation-update',
    templateUrl: './flock-relation-update.component.html'
})
export class FlockRelationUpdateComponent implements OnInit {
    private _flockRelation: IFlockRelation;
    isSaving: boolean;

    customers: ICustomer[];

    customerflocks: ICustomerFlock[];
    createdDate: string;

    constructor(
        private jhiAlertService: JhiAlertService,
        private flockRelationService: FlockRelationService,
        private customerService: CustomerService,
        private customerFlockService: CustomerFlockService,
        private activatedRoute: ActivatedRoute
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ flockRelation }) => {
            this.flockRelation = flockRelation;
        });
        this.customerService.query().subscribe(
            (res: HttpResponse<ICustomer[]>) => {
                this.customers = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
        this.customerFlockService.query().subscribe(
            (res: HttpResponse<ICustomerFlock[]>) => {
                this.customerflocks = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        this.flockRelation.createdDate = moment(this.createdDate, DATE_TIME_FORMAT);
        if (this.flockRelation.id !== undefined) {
            this.subscribeToSaveResponse(this.flockRelationService.update(this.flockRelation));
        } else {
            this.subscribeToSaveResponse(this.flockRelationService.create(this.flockRelation));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<IFlockRelation>>) {
        result.subscribe((res: HttpResponse<IFlockRelation>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }

    trackCustomerById(index: number, item: ICustomer) {
        return item.id;
    }

    trackCustomerFlockById(index: number, item: ICustomerFlock) {
        return item.id;
    }
    get flockRelation() {
        return this._flockRelation;
    }

    set flockRelation(flockRelation: IFlockRelation) {
        this._flockRelation = flockRelation;
        this.createdDate = moment(flockRelation.createdDate).format(DATE_TIME_FORMAT);
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="jhi-flock-relation-heading" jhiTranslate="imGatewayApp.flockRelation.home.createOrEditLabel">Create or edit a Flock Relation</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!flockRelation.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="flockRelation.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.flockRelation.remarkName" for="field_remarkName" [ngbTooltip]="'imGatewayApp.flockRelation.help.remarkName' | translate">Remark Name</label>
                    <input type="text" class="form-control" name="remarkName" id="field_remarkName"
                        [(ngModel)]="flockRelation.remarkName" minlength="2" maxlength="14"/>
                    <div [hidden]="!(editForm.controls.remarkName?.dirty && editForm.controls.remarkName?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.remarkName?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 2 }">
                        This field is required to be at least 2 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.remarkName?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 14 }">
                        This field cannot be longer than 14 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.flockRelation.py" for="field_py" [ngbTooltip]="'imGatewayApp.flockRelation.help.py' | translate">Py</label>
                    <input type="text" class="form-control" name="py" id="field_py"
                        [(ngModel)]="flockRelation.py" required minlength="1" maxlength="255"/>
                    <div [hidden]="!(editForm.controls.py?.dirty && editForm.controls.py?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.py?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.py?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.py?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 255 }">
                        This field cannot be longer than 255 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.flockRelation.pinYin" for="field_pinYin" [ngbTooltip]="'imGatewayApp.flockRelation.help.pinYin' | translate">Pin Yin</label>
                    <input type="text" class="form-control" name="pinYin" id="field_pinYin"
                        [(ngModel)]="flockRelation.pinYin" required minlength="1" maxlength="255"/>
                    <div [hidden]="!(editForm.controls.pinYin?.dirty && editForm.controls.pinYin?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.pinYin?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.pinYin?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.pinYin?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 255 }">
                        This field cannot be longer than 255 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.flockRelation.type" for="field_type" [ngbTooltip]="'imGatewayApp.flockRelation.help.type' | translate">Type</label>
                    <input type="text" class="form-control" name="type" id="field_type"
                        [(ngModel)]="flockRelation.type" required minlength="1" maxlength="2"/>
                    <div [hidden]="!(editForm.controls.type?.dirty && editForm.controls.type?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.type?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.type?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.type?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 2 }">
                        This field cannot be longer than 2 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.flockRelation.createdDate" for="field_createdDate" [ngbTooltip]="'imGatewayApp.flockRelation.help.createdDate' | translate">Created Date</label>
                    <div class="d-flex">
                        <input id="field_createdDate" type="datetime-local" class="form-control" name="createdDate" [(ngModel)]="createdDate"
                        required/>
                    </div>
                    <div [hidden]="!(editForm.controls.createdDate?.dirty && editForm.controls.createdDate?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.createdDate?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.createdDate?.errors?.ZonedDateTimelocal" jhiTranslate="entity.validation.ZonedDateTimelocal">
                            This field should be a date and time.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.flockRelation.customer" for="field_customer">Customer</label>
                    <select class="form-control" id="field_customer" name="customer" [(ngModel)]="flockRelation.customerId" >
                        <option [ngValue]="null"></option>
                        <option [ngValue]="customerOption.id" *ngFor="let customerOption of customers; trackBy: trackCustomerById">{{customerOption.firstName}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.flockRelation.customerFlock" for="field_customerFlock">Customer Flock</label>
                    <select class="form-control" id="field_customerFlock" name="customerFlock" [(ngModel)]="flockRelation.customerFlockId" >
                        <option [ngValue]="null"></option>
                        <option [ngValue]="customerFlockOption.id" *ngFor="let customerFlockOption of customerflocks; trackBy: trackCustomerFlockById">{{customerFlockOption.name}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// x-im-web-new/src/main/webapp/app/entities/flock-relation/flock-relation-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label, UncontrolledTooltip } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { ICustomer } from 'app/shared/model/customer.model';
import { getEntities as getCustomers } from 'app/entities/customer/customer.reducer';
import { ICustomerFlock } from 'app/shared/model/customer-flock.model';
import { getEntities as getCustomerFlocks } from 'app/entities/customer-flock/customer-flock.reducer';
import { getEntity, updateEntity, createEntity, reset } from 'app/entities/flock-relation/flock-relation.reducer';
import { IFlockRelation } from 'app/shared/model/flock-relation.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { keysToValues } from 'app/shared/util/entity-utils';

export interface IFlockRelationUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: number }> {}

export interface IFlockRelationUpdateState {
  isNew: boolean;
  customerId: number;
  customerFlockId: number;
}

export class FlockRelationUpdate extends React.Component<IFlockRelationUpdateProps, IFlockRelationUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      customerId: 0,
      customerFlockId: 0,
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getCustomers();
    this.props.getCustomerFlocks();
  }

  saveEntity = (event, errors, values) => {
    values.createdDate = new Date(values.createdDate);

    if (errors.length === 0) {
      const { flockRelationEntity } = this.props;
      const entity = {
        ...flockRelationEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
      this.handleClose();
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/flock-relation');
  };

  customerUpdate = element => {
    const firstName = element.target.value.toString();
    if (firstName === '') {
      this.setState({
        customerId: -1
      });
    } else {
      for (const i in this.props.customers) {
        if (firstName === this.props.customers[i].firstName.toString()) {
          this.setState({
            customerId: this.props.customers[i].id
          });
        }
      }
    }
  };

  customerFlockUpdate = element => {
    const name = element.target.value.toString();
    if (name === '') {
      this.setState({
        customerFlockId: -1
      });
    } else {
      for (const i in this.props.customerFlocks) {
        if (name === this.props.customerFlocks[i].name.toString()) {
          this.setState({
            customerFlockId: this.props.customerFlocks[i].id
          });
        }
      }
    }
  };

  render() {
    const { flockRelationEntity, customers, customerFlocks, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="imWebGatewayApp.flockRelation.home.createOrEditLabel">
              <Translate contentKey="imWebGatewayApp.flockRelation.home.createOrEditLabel">Create or edit a FlockRelation</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : flockRelationEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="flock-relation-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="remarkNameLabel" for="remarkName">
                    <Translate contentKey="imWebGatewayApp.flockRelation.remarkName">Remark Name</Translate>
                  </Label>
                  <AvField
                    id="flock-relation-remarkName"
                    type="text"
                    name="remarkName"
                    validate={{
                      minLength: { value: 2, errorMessage: translate('entity.validation.minlength', { min: 2 }) },
                      maxLength: { value: 14, errorMessage: translate('entity.validation.maxlength', { max: 14 }) }
                    }}
                  />
                  <UncontrolledTooltip target="remarkNameLabel">
                    <Translate contentKey="imWebGatewayApp.flockRelation.help.remarkName" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="pyLabel" for="py">
                    <Translate contentKey="imWebGatewayApp.flockRelation.py">Py</Translate>
                  </Label>
                  <AvField
                    id="flock-relation-py"
                    type="text"
                    name="py"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 255, errorMessage: translate('entity.validation.maxlength', { max: 255 }) }
                    }}
                  />
                  <UncontrolledTooltip target="pyLabel">
                    <Translate contentKey="imWebGatewayApp.flockRelation.help.py" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="pinYinLabel" for="pinYin">
                    <Translate contentKey="imWebGatewayApp.flockRelation.pinYin">Pin Yin</Translate>
                  </Label>
                  <AvField
                    id="flock-relation-pinYin"
                    type="text"
                    name="pinYin"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 255, errorMessage: translate('entity.validation.maxlength', { max: 255 }) }
                    }}
                  />
                  <UncontrolledTooltip target="pinYinLabel">
                    <Translate contentKey="imWebGatewayApp.flockRelation.help.pinYin" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="typeLabel" for="type">
                    <Translate contentKey="imWebGatewayApp.flockRelation.type">Type</Translate>
                  </Label>
                  <AvField
                    id="flock-relation-type"
                    type="text"
                    name="type"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 2, errorMessage: translate('entity.validation.maxlength', { max: 2 }) }
                    }}
                  />
                  <UncontrolledTooltip target="typeLabel">
                    <Translate contentKey="imWebGatewayApp.flockRelation.help.type" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="createdDateLabel" for="createdDate">
                    <Translate contentKey="imWebGatewayApp.flockRelation.createdDate">Created Date</Translate>
                  </Label>
                  <AvInput
                    id="flock-relation-createdDate"
                    type="datetime-local"
                    className="form-control"
                    name="createdDate"
                    value={isNew ? null : convertDateTimeFromServer(this.props.flockRelationEntity.createdDate)}
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                  <UncontrolledTooltip target="createdDateLabel">
                    <Translate contentKey="imWebGatewayApp.flockRelation.help.createdDate" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label for="customer.firstName">
                    <Translate contentKey="imWebGatewayApp.flockRelation.customer">Customer</Translate>
                  </Label>
                  <AvInput
                    id="flock-relation-customer"
                    type="select"
                    className="form-control"
                    name="customerId"
                    onChange={this.customerUpdate}
                  >
                    <option value="" key="0" />
                    {customers
                      ? customers.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.firstName}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="customerFlock.name">
                    <Translate contentKey="imWebGatewayApp.flockRelation.customerFlock">Customer Flock</Translate>
                  </Label>
                  <AvInput
                    id="flock-relation-customerFlock"
                    type="select"
                    className="form-control"
                    name="customerFlockId"
                    onChange={this.customerFlockUpdate}
                  >
                    <option value="" key="0" />
                    {customerFlocks
                      ? customerFlocks.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.name}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/flock-relation" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  customers: storeState.customer.entities,
  customerFlocks: storeState.customerFlock.entities,
  flockRelationEntity: storeState.flockRelation.entity,
  loading: storeState.flockRelation.loading,
  updating: storeState.flockRelation.updating
});

const mapDispatchToProps = {
  getCustomers,
  getCustomerFlocks,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(FlockRelationUpdate);
