// x-manage-web/src/main/webapp/app/entities/flock-relation/flock-relation-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, UncontrolledTooltip, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './flock-relation.reducer';
import { IFlockRelation } from 'app/shared/model/flock-relation.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IFlockRelationDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: number }> {}

export class FlockRelationDetail extends React.Component<IFlockRelationDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { flockRelationEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="manageGatewayApp.flockRelation.detail.title">FlockRelation</Translate> [<b>{flockRelationEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="remarkName">
                <Translate contentKey="manageGatewayApp.flockRelation.remarkName">Remark Name</Translate>
              </span>
              <UncontrolledTooltip target="remarkName">
                <Translate contentKey="manageGatewayApp.flockRelation.help.remarkName" />
              </UncontrolledTooltip>
            </dt>
            <dd>{flockRelationEntity.remarkName}</dd>
            <dt>
              <span id="py">
                <Translate contentKey="manageGatewayApp.flockRelation.py">Py</Translate>
              </span>
              <UncontrolledTooltip target="py">
                <Translate contentKey="manageGatewayApp.flockRelation.help.py" />
              </UncontrolledTooltip>
            </dt>
            <dd>{flockRelationEntity.py}</dd>
            <dt>
              <span id="pinYin">
                <Translate contentKey="manageGatewayApp.flockRelation.pinYin">Pin Yin</Translate>
              </span>
              <UncontrolledTooltip target="pinYin">
                <Translate contentKey="manageGatewayApp.flockRelation.help.pinYin" />
              </UncontrolledTooltip>
            </dt>
            <dd>{flockRelationEntity.pinYin}</dd>
            <dt>
              <span id="type">
                <Translate contentKey="manageGatewayApp.flockRelation.type">Type</Translate>
              </span>
              <UncontrolledTooltip target="type">
                <Translate contentKey="manageGatewayApp.flockRelation.help.type" />
              </UncontrolledTooltip>
            </dt>
            <dd>{flockRelationEntity.type}</dd>
            <dt>
              <span id="createdDate">
                <Translate contentKey="manageGatewayApp.flockRelation.createdDate">Created Date</Translate>
              </span>
              <UncontrolledTooltip target="createdDate">
                <Translate contentKey="manageGatewayApp.flockRelation.help.createdDate" />
              </UncontrolledTooltip>
            </dt>
            <dd>
              <TextFormat value={flockRelationEntity.createdDate} type="date" format={APP_DATE_FORMAT} />
            </dd>
            <dt>
              <Translate contentKey="manageGatewayApp.flockRelation.customer">Customer</Translate>
            </dt>
            <dd>{flockRelationEntity.customerFirstName ? flockRelationEntity.customerFirstName : ''}</dd>
            <dt>
              <Translate contentKey="manageGatewayApp.flockRelation.customerFlock">Customer Flock</Translate>
            </dt>
            <dd>{flockRelationEntity.customerFlockName ? flockRelationEntity.customerFlockName : ''}</dd>
          </dl>
          <Button tag={Link} to="/entity/flock-relation" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>&nbsp;
          <Button tag={Link} to={`/entity/flock-relation/${flockRelationEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ flockRelation }: IRootState) => ({
  flockRelationEntity: flockRelation.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(FlockRelationDetail);

// x-demo-hybrid-gateway/src/main/webapp/app/entities/flock-relation/flock-relation-detail.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs/Subscription';
import { JhiEventManager } from 'ng-jhipster';

import { FlockRelation } from './flock-relation.model';
import { FlockRelationService } from './flock-relation.service';

@Component({
    selector: 'jhi-flock-relation-detail',
    templateUrl: './flock-relation-detail.component.html'
})
export class FlockRelationDetailComponent implements OnInit, OnDestroy {

    flockRelation: FlockRelation;
    private subscription: Subscription;
    private eventSubscriber: Subscription;

    constructor(
        private eventManager: JhiEventManager,
        private flockRelationService: FlockRelationService,
        private route: ActivatedRoute
    ) {
    }

    ngOnInit() {
        this.subscription = this.route.params.subscribe((params) => {
            this.load(params['id']);
        });
        this.registerChangeInFlockRelations();
    }

    load(id) {
        this.flockRelationService.find(id)
            .subscribe((flockRelationResponse: HttpResponse<FlockRelation>) => {
                this.flockRelation = flockRelationResponse.body;
            });
    }
    previousState() {
        window.history.back();
    }

    ngOnDestroy() {
        this.subscription.unsubscribe();
        this.eventManager.destroy(this.eventSubscriber);
    }

    registerChangeInFlockRelations() {
        this.eventSubscriber = this.eventManager.subscribe(
            'flockRelationListModification',
            (response) => this.load(this.flockRelation.id)
        );
    }
}


<div *ngIf="flockRelation">
    <h2><span jhiTranslate="demoHybridGatewayApp.flockRelation.detail.title">Flock Relation</span> {{flockRelation.id}}</h2>
    <hr>
    <jhi-alert-error></jhi-alert-error>
    <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="demoHybridGatewayApp.flockRelation.remarkName" [ngbTooltip]="'demoHybridGatewayApp.flockRelation.help.remarkName' | translate">Remark Name</span></dt>
        <dd>
            <span>{{flockRelation.remarkName}}</span>
        </dd>
        <dt><span jhiTranslate="demoHybridGatewayApp.flockRelation.py" [ngbTooltip]="'demoHybridGatewayApp.flockRelation.help.py' | translate">Py</span></dt>
        <dd>
            <span>{{flockRelation.py}}</span>
        </dd>
        <dt><span jhiTranslate="demoHybridGatewayApp.flockRelation.pinYin" [ngbTooltip]="'demoHybridGatewayApp.flockRelation.help.pinYin' | translate">Pin Yin</span></dt>
        <dd>
            <span>{{flockRelation.pinYin}}</span>
        </dd>
        <dt><span jhiTranslate="demoHybridGatewayApp.flockRelation.type" [ngbTooltip]="'demoHybridGatewayApp.flockRelation.help.type' | translate">Type</span></dt>
        <dd>
            <span>{{flockRelation.type}}</span>
        </dd>
        <dt><span jhiTranslate="demoHybridGatewayApp.flockRelation.createdDate" [ngbTooltip]="'demoHybridGatewayApp.flockRelation.help.createdDate' | translate">Created Date</span></dt>
        <dd>
            <span>{{flockRelation.createdDate | date:'medium'}}</span>
        </dd>
        <dt><span jhiTranslate="demoHybridGatewayApp.flockRelation.customer">Customer</span></dt>
        <dd>
            <div *ngIf="flockRelation.customerId">
                <a [routerLink]="['/customer', flockRelation.customerId]">{{flockRelation.customerFirstName}}</a>
            </div>
        </dd>
        <dt><span jhiTranslate="demoHybridGatewayApp.flockRelation.customerFlock">Customer Flock</span></dt>
        <dd>
            <div *ngIf="flockRelation.customerFlockId">
                <a [routerLink]="['/customer-flock', flockRelation.customerFlockId]">{{flockRelation.customerFlockName}}</a>
            </div>
        </dd>
    </dl>

    <button type="submit"
            (click)="previousState()"
            class="btn btn-info">
        <span class="fa fa-arrow-left"></span>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
    </button>

    <button type="button"
            [routerLink]="['/', { outlets: { popup: 'flock-relation/'+ flockRelation.id + '/edit'} }]"
            replaceUrl="true"
            queryParamsHandling="merge"
            class="btn btn-primary">
        <span class="fa fa-pencil"></span>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
    </button>
</div>
