// x-im-web-new/src/main/webapp/app/entities/customer-flock/customer-flock-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label, UncontrolledTooltip } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from 'app/entities/customer-flock/customer-flock.reducer';
import { ICustomerFlock } from 'app/shared/model/customer-flock.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
// import { keysToValues } from 'app/shared/util/entity-utils';

export interface ICustomerFlockUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string}> {}

export interface ICustomerFlockUpdateState {
  isNew: boolean;
}

export class CustomerFlockUpdate extends React.Component<ICustomerFlockUpdateProps, ICustomerFlockUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }
  }

  saveEntity = (event, errors, values) => {
    values.createdDate = new Date(values.createdDate);

    if (errors.length === 0) {
      const { customerFlockEntity } = this.props;
      const entity = {
        ...customerFlockEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
      this.handleClose();
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/customer-flock');
  };

  render() {
    const { customerFlockEntity, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="imWebGatewayApp.customerFlock.home.createOrEditLabel">
              <Translate contentKey="imWebGatewayApp.customerFlock.home.createOrEditLabel">Create or edit a CustomerFlock</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : customerFlockEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="customer-flock-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="nameLabel" for="name">
                    <Translate contentKey="imWebGatewayApp.customerFlock.name">Name</Translate>
                  </Label>
                  <AvField
                    id="customer-flock-name"
                    type="text"
                    name="name"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 2, errorMessage: translate('entity.validation.minlength', { min: 2 }) },
                      maxLength: { value: 14, errorMessage: translate('entity.validation.maxlength', { max: 14 }) }
                    }}
                  />
                  <UncontrolledTooltip target="nameLabel">
                    <Translate contentKey="imWebGatewayApp.customerFlock.help.name" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="pyLabel" for="py">
                    <Translate contentKey="imWebGatewayApp.customerFlock.py">Py</Translate>
                  </Label>
                  <AvField
                    id="customer-flock-py"
                    type="text"
                    name="py"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 255, errorMessage: translate('entity.validation.maxlength', { max: 255 }) }
                    }}
                  />
                  <UncontrolledTooltip target="pyLabel">
                    <Translate contentKey="imWebGatewayApp.customerFlock.help.py" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="pinYinLabel" for="pinYin">
                    <Translate contentKey="imWebGatewayApp.customerFlock.pinYin">Pin Yin</Translate>
                  </Label>
                  <AvField
                    id="customer-flock-pinYin"
                    type="text"
                    name="pinYin"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 255, errorMessage: translate('entity.validation.maxlength', { max: 255 }) }
                    }}
                  />
                  <UncontrolledTooltip target="pinYinLabel">
                    <Translate contentKey="imWebGatewayApp.customerFlock.help.pinYin" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="imageUrlLabel" for="imageUrl">
                    <Translate contentKey="imWebGatewayApp.customerFlock.imageUrl">Image Url</Translate>
                  </Label>
                  <AvField
                    id="customer-flock-imageUrl"
                    type="text"
                    name="imageUrl"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      maxLength: { value: 255, errorMessage: translate('entity.validation.maxlength', { max: 255 }) }
                    }}
                  />
                  <UncontrolledTooltip target="imageUrlLabel">
                    <Translate contentKey="imWebGatewayApp.customerFlock.help.imageUrl" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="createdDateLabel" for="createdDate">
                    <Translate contentKey="imWebGatewayApp.customerFlock.createdDate">Created Date</Translate>
                  </Label>
                  <AvInput
                    id="customer-flock-createdDate"
                    type="datetime-local"
                    className="form-control"
                    name="createdDate"
                    value={isNew ? null : convertDateTimeFromServer(this.props.customerFlockEntity.createdDate)}
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                  <UncontrolledTooltip target="createdDateLabel">
                    <Translate contentKey="imWebGatewayApp.customerFlock.help.createdDate" />
                  </UncontrolledTooltip>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/customer-flock" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />&nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />&nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  customerFlockEntity: storeState.customerFlock.entity,
  loading: storeState.customerFlock.loading,
  updating: storeState.customerFlock.updating
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CustomerFlockUpdate);

// x-im-desktop-gateway/src/main/webapp/app/entities/customer-flock/customer-flock-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import * as moment from 'moment';
import { DATE_TIME_FORMAT } from 'app/shared/constants/input.constants';

import { ICustomerFlock } from 'app/shared/model/customer-flock.model';
import { CustomerFlockService } from './customer-flock.service';

@Component({
    selector: 'jhi-customer-flock-update',
    templateUrl: './customer-flock-update.component.html'
})
export class CustomerFlockUpdateComponent implements OnInit {
    private _customerFlock: ICustomerFlock;
    isSaving: boolean;
    createdDate: string;

    constructor(private customerFlockService: CustomerFlockService, private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ customerFlock }) => {
            this.customerFlock = customerFlock;
        });
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        this.customerFlock.createdDate = moment(this.createdDate, DATE_TIME_FORMAT);
        if (this.customerFlock.id !== undefined) {
            this.subscribeToSaveResponse(this.customerFlockService.update(this.customerFlock));
        } else {
            this.subscribeToSaveResponse(this.customerFlockService.create(this.customerFlock));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<ICustomerFlock>>) {
        result.subscribe((res: HttpResponse<ICustomerFlock>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }
    get customerFlock() {
        return this._customerFlock;
    }

    set customerFlock(customerFlock: ICustomerFlock) {
        this._customerFlock = customerFlock;
        this.createdDate = moment(customerFlock.createdDate).format(DATE_TIME_FORMAT);
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="jhi-customer-flock-heading" jhiTranslate="imGatewayApp.customerFlock.home.createOrEditLabel">Create or edit a Customer Flock</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!customerFlock.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="customerFlock.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customerFlock.name" for="field_name" [ngbTooltip]="'imGatewayApp.customerFlock.help.name' | translate">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                        [(ngModel)]="customerFlock.name" required minlength="2" maxlength="14"/>
                    <div [hidden]="!(editForm.controls.name?.dirty && editForm.controls.name?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.name?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.name?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 2 }">
                        This field is required to be at least 2 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.name?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 14 }">
                        This field cannot be longer than 14 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customerFlock.py" for="field_py" [ngbTooltip]="'imGatewayApp.customerFlock.help.py' | translate">Py</label>
                    <input type="text" class="form-control" name="py" id="field_py"
                        [(ngModel)]="customerFlock.py" required minlength="1" maxlength="255"/>
                    <div [hidden]="!(editForm.controls.py?.dirty && editForm.controls.py?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.py?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.py?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.py?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 255 }">
                        This field cannot be longer than 255 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customerFlock.pinYin" for="field_pinYin" [ngbTooltip]="'imGatewayApp.customerFlock.help.pinYin' | translate">Pin Yin</label>
                    <input type="text" class="form-control" name="pinYin" id="field_pinYin"
                        [(ngModel)]="customerFlock.pinYin" required minlength="1" maxlength="255"/>
                    <div [hidden]="!(editForm.controls.pinYin?.dirty && editForm.controls.pinYin?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.pinYin?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.pinYin?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.pinYin?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 255 }">
                        This field cannot be longer than 255 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customerFlock.imageUrl" for="field_imageUrl" [ngbTooltip]="'imGatewayApp.customerFlock.help.imageUrl' | translate">Image Url</label>
                    <input type="text" class="form-control" name="imageUrl" id="field_imageUrl"
                        [(ngModel)]="customerFlock.imageUrl" required maxlength="255"/>
                    <div [hidden]="!(editForm.controls.imageUrl?.dirty && editForm.controls.imageUrl?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.imageUrl?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.imageUrl?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 255 }">
                        This field cannot be longer than 255 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.customerFlock.createdDate" for="field_createdDate" [ngbTooltip]="'imGatewayApp.customerFlock.help.createdDate' | translate">Created Date</label>
                    <div class="d-flex">
                        <input id="field_createdDate" type="datetime-local" class="form-control" name="createdDate" [(ngModel)]="createdDate"
                        required/>
                    </div>
                    <div [hidden]="!(editForm.controls.createdDate?.dirty && editForm.controls.createdDate?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.createdDate?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.createdDate?.errors?.ZonedDateTimelocal" jhiTranslate="entity.validation.ZonedDateTimelocal">
                            This field should be a date and time.
                        </small>
                    </div>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
