// x-im-monolithic/src/main/webapp/app/entities/history-message/history-message-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label, UncontrolledTooltip } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './history-message.reducer';
import { IHistoryMessage } from 'app/shared/model/history-message.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IHistoryMessageUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface IHistoryMessageUpdateState {
  isNew: boolean;
}

export class HistoryMessageUpdate extends React.Component<IHistoryMessageUpdateProps, IHistoryMessageUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }
  }

  saveEntity = (event, errors, values) => {
    values.createdDate = new Date(values.createdDate);
    values.targetDate = new Date(values.targetDate);

    if (errors.length === 0) {
      const { historyMessageEntity } = this.props;
      const entity = {
        ...historyMessageEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/history-message');
  };

  render() {
    const { historyMessageEntity, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="imApp.historyMessage.home.createOrEditLabel">
              <Translate contentKey="imApp.historyMessage.home.createOrEditLabel">Create or edit a HistoryMessage</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : historyMessageEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="history-message-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="contentLabel" for="content">
                    <Translate contentKey="imApp.historyMessage.content">Content</Translate>
                  </Label>
                  <AvField
                    id="history-message-content"
                    type="text"
                    name="content"
                    validate={{
                      minLength: { value: 2, errorMessage: translate('entity.validation.minlength', { min: 2 }) },
                      maxLength: { value: 14, errorMessage: translate('entity.validation.maxlength', { max: 14 }) }
                    }}
                  />
                  <UncontrolledTooltip target="contentLabel">
                    <Translate contentKey="imApp.historyMessage.help.content" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="statusLabel" for="status">
                    <Translate contentKey="imApp.historyMessage.status">Status</Translate>
                  </Label>
                  <AvField
                    id="history-message-status"
                    type="text"
                    name="status"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      minLength: { value: 1, errorMessage: translate('entity.validation.minlength', { min: 1 }) },
                      maxLength: { value: 2, errorMessage: translate('entity.validation.maxlength', { max: 2 }) }
                    }}
                  />
                  <UncontrolledTooltip target="statusLabel">
                    <Translate contentKey="imApp.historyMessage.help.status" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="createdDateLabel" for="createdDate">
                    <Translate contentKey="imApp.historyMessage.createdDate">Created Date</Translate>
                  </Label>
                  <AvInput
                    id="history-message-createdDate"
                    type="datetime-local"
                    className="form-control"
                    name="createdDate"
                    value={isNew ? null : convertDateTimeFromServer(this.props.historyMessageEntity.createdDate)}
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                  <UncontrolledTooltip target="createdDateLabel">
                    <Translate contentKey="imApp.historyMessage.help.createdDate" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="createdIdLabel" for="createdId">
                    <Translate contentKey="imApp.historyMessage.createdId">Created Id</Translate>
                  </Label>
                  <AvField
                    id="history-message-createdId"
                    type="string"
                    className="form-control"
                    name="createdId"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      number: { value: true, errorMessage: translate('entity.validation.number') }
                    }}
                  />
                  <UncontrolledTooltip target="createdIdLabel">
                    <Translate contentKey="imApp.historyMessage.help.createdId" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="targetDateLabel" for="targetDate">
                    <Translate contentKey="imApp.historyMessage.targetDate">Target Date</Translate>
                  </Label>
                  <AvInput
                    id="history-message-targetDate"
                    type="datetime-local"
                    className="form-control"
                    name="targetDate"
                    value={isNew ? null : convertDateTimeFromServer(this.props.historyMessageEntity.targetDate)}
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                  <UncontrolledTooltip target="targetDateLabel">
                    <Translate contentKey="imApp.historyMessage.help.targetDate" />
                  </UncontrolledTooltip>
                </AvGroup>
                <AvGroup>
                  <Label id="targetIdLabel" for="targetId">
                    <Translate contentKey="imApp.historyMessage.targetId">Target Id</Translate>
                  </Label>
                  <AvField
                    id="history-message-targetId"
                    type="string"
                    className="form-control"
                    name="targetId"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      number: { value: true, errorMessage: translate('entity.validation.number') }
                    }}
                  />
                  <UncontrolledTooltip target="targetIdLabel">
                    <Translate contentKey="imApp.historyMessage.help.targetId" />
                  </UncontrolledTooltip>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/history-message" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  historyMessageEntity: storeState.historyMessage.entity,
  loading: storeState.historyMessage.loading,
  updating: storeState.historyMessage.updating,
  updateSuccess: storeState.historyMessage.updateSuccess
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(HistoryMessageUpdate);

// x-im-desktop-gateway/src/main/webapp/app/entities/history-message/history-message-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import * as moment from 'moment';
import { DATE_TIME_FORMAT } from 'app/shared/constants/input.constants';

import { IHistoryMessage } from 'app/shared/model/history-message.model';
import { HistoryMessageService } from './history-message.service';

@Component({
    selector: 'jhi-history-message-update',
    templateUrl: './history-message-update.component.html'
})
export class HistoryMessageUpdateComponent implements OnInit {
    private _historyMessage: IHistoryMessage;
    isSaving: boolean;
    createdDate: string;
    targetDate: string;

    constructor(private historyMessageService: HistoryMessageService, private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ historyMessage }) => {
            this.historyMessage = historyMessage;
        });
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        this.historyMessage.createdDate = moment(this.createdDate, DATE_TIME_FORMAT);
        this.historyMessage.targetDate = moment(this.targetDate, DATE_TIME_FORMAT);
        if (this.historyMessage.id !== undefined) {
            this.subscribeToSaveResponse(this.historyMessageService.update(this.historyMessage));
        } else {
            this.subscribeToSaveResponse(this.historyMessageService.create(this.historyMessage));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<IHistoryMessage>>) {
        result.subscribe((res: HttpResponse<IHistoryMessage>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }
    get historyMessage() {
        return this._historyMessage;
    }

    set historyMessage(historyMessage: IHistoryMessage) {
        this._historyMessage = historyMessage;
        this.createdDate = moment(historyMessage.createdDate).format(DATE_TIME_FORMAT);
        this.targetDate = moment(historyMessage.targetDate).format(DATE_TIME_FORMAT);
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="jhi-history-message-heading" jhiTranslate="imGatewayApp.historyMessage.home.createOrEditLabel">Create or edit a History Message</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!historyMessage.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="historyMessage.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.historyMessage.content" for="field_content" [ngbTooltip]="'imGatewayApp.historyMessage.help.content' | translate">Content</label>
                    <input type="text" class="form-control" name="content" id="field_content"
                        [(ngModel)]="historyMessage.content" minlength="2" maxlength="14"/>
                    <div [hidden]="!(editForm.controls.content?.dirty && editForm.controls.content?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.content?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 2 }">
                        This field is required to be at least 2 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.content?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 14 }">
                        This field cannot be longer than 14 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.historyMessage.status" for="field_status" [ngbTooltip]="'imGatewayApp.historyMessage.help.status' | translate">Status</label>
                    <input type="text" class="form-control" name="status" id="field_status"
                        [(ngModel)]="historyMessage.status" required minlength="1" maxlength="2"/>
                    <div [hidden]="!(editForm.controls.status?.dirty && editForm.controls.status?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.status?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.status?.errors?.minlength" jhiTranslate="entity.validation.minlength" translateValues="{ min: 1 }">
                        This field is required to be at least 1 characters.
                        </small>
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.status?.errors?.maxlength" jhiTranslate="entity.validation.maxlength" translateValues="{ max: 2 }">
                        This field cannot be longer than 2 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.historyMessage.createdDate" for="field_createdDate" [ngbTooltip]="'imGatewayApp.historyMessage.help.createdDate' | translate">Created Date</label>
                    <div class="d-flex">
                        <input id="field_createdDate" type="datetime-local" class="form-control" name="createdDate" [(ngModel)]="createdDate"
                        required/>
                    </div>
                    <div [hidden]="!(editForm.controls.createdDate?.dirty && editForm.controls.createdDate?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.createdDate?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.createdDate?.errors?.ZonedDateTimelocal" jhiTranslate="entity.validation.ZonedDateTimelocal">
                            This field should be a date and time.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.historyMessage.createdId" for="field_createdId" [ngbTooltip]="'imGatewayApp.historyMessage.help.createdId' | translate">Created Id</label>
                    <input type="number" class="form-control" name="createdId" id="field_createdId"
                        [(ngModel)]="historyMessage.createdId" required/>
                    <div [hidden]="!(editForm.controls.createdId?.dirty && editForm.controls.createdId?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.createdId?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.createdId?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.historyMessage.targetDate" for="field_targetDate" [ngbTooltip]="'imGatewayApp.historyMessage.help.targetDate' | translate">Target Date</label>
                    <div class="d-flex">
                        <input id="field_targetDate" type="datetime-local" class="form-control" name="targetDate" [(ngModel)]="targetDate"
                        required/>
                    </div>
                    <div [hidden]="!(editForm.controls.targetDate?.dirty && editForm.controls.targetDate?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.targetDate?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.targetDate?.errors?.ZonedDateTimelocal" jhiTranslate="entity.validation.ZonedDateTimelocal">
                            This field should be a date and time.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="imGatewayApp.historyMessage.targetId" for="field_targetId" [ngbTooltip]="'imGatewayApp.historyMessage.help.targetId' | translate">Target Id</label>
                    <input type="number" class="form-control" name="targetId" id="field_targetId"
                        [(ngModel)]="historyMessage.targetId" required/>
                    <div [hidden]="!(editForm.controls.targetId?.dirty && editForm.controls.targetId?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.targetId?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.targetId?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
